const ALLERGY_FACTS=[
{cat:"Allergens & Mods",q:"Fully vegan dishes as printed (VG)?",a:"Encurtidos, Pan a la Catalana, Pimientos de Padrón, Primavera paella",x:"Ajo Blanco is vegan without the jamón. Escalivada is printed V only — ask Chef"},
{cat:"Allergens & Mods",q:"Vegetarian traps on the menu?",a:"Flor de Alcachofa (anchovy aioli), Goxua (pork gelatin), Quesos y Charcutería (meat), Setas is V but not GF (shoyu)",x:"Flor de Alcachofa is vegetarian if you sub garlic aioli"},
{cat:"Allergens & Mods",q:"Gluten-free paellas?",a:"Señorito, Valenciana, Rabo de Toro, Americana, Primavera — NOT the Marinera Fideuà",x:"Fideo = wheat noodle"},
{cat:"Allergens & Mods",q:"Dairy-free tapas as printed (DF)?",a:"Crudo de Atún, Patatas Bravas, Dátiles, Pluma Katsu, Flor de Alcachofa, Pintxos Morunos — plus Padrón (vegan)",x:"Aioli is egg + oil, not dairy. Pulpo needs no-potatoes; Berenjena needs no-blue-cheese"},
{cat:"Allergens & Mods",q:"Gluten-free desserts?",a:"Tarta de Santiago (almond) and Goxua (GF chiffon)",x:"Goxua has pork gelatin — GF but not vegetarian"},
{cat:"Allergens & Mods",q:"Pescatarian guest — what's off limits besides meat?",a:"Dátiles (chorizo, bacon), Croquetas de Jamón, Pluma Katsu, Valenciana, Rabo de Toro, Americana, Goxua (gelatin), Ajo Blanco unless no-jamón",x:"Happy hour: Jamón y Manchego & Papas Fritas y Jamón too"},
{cat:"Allergens & Mods",q:"What's in the shared fryer? (cross-contact)",a:"Nightshade, dairy, gluten, fin fish, jamón, eggs",x:"Anything fried (bravas, croquetas, buñuelos, padrón, berenjena, katsu, pepa, chips) carries this cross-contact"},
{cat:"Allergens & Mods",q:"Which dessert contains pork?",a:"Goxua — porcine gelatin in the curd",x:"Not vegetarian, not halal/kosher"},
{cat:"Allergens & Mods",q:"Hidden fin-fish allergen in the Pluma Katsu?",a:"Worcestershire (anchovy) in the sherry tonkatsu sauce",x:"Katsu sauce on the side does NOT make it safe — sauce still touches the plate"},
{cat:"Allergens & Mods",q:"Is the Marinera Fideuà gluten-free?",a:"No — fideo noodles are wheat pasta",x:"Rice paellas are printed GF"},
{cat:"Allergens & Mods",q:"Which dessert is naturally gluten-free?",a:"Tarta de Santiago — almond flour, sugar, eggs",x:"Contains tree nuts · served with ice cream (dairy)"},
{cat:"Allergens & Mods",q:"Guest is pregnant and orders the cheese board?",a:"Pasteurized cheeses only, no goat's milk — check with Chef for swaps",x:"Same rule for charcuterie: no sausage, no dairy powder"},
{cat:"Allergens & Mods",q:"Pintxos Morunos for a gluten-free guest?",a:"Ask Chef to prepare the meat separately — normal prep has gluten cross-contact",x:""},
{cat:"Allergens & Mods",q:"Which items have tree nuts?",a:"Croquetas de Jamón (hazelnut romesco), Ajo Blanco (almond), Almendras y Piña, Quesos boards (Marcona), Tarta de Santiago, Bizcocho (pistachio)",x:"Romesco on the side or sub quince for the croquetas"},
{cat:"Allergens & Mods",q:"Which items are crustacean/shellfish?",a:"Gambas, Señorito, Marinera Fideuà (crab & shrimp)",x:"Pulpo is mollusk; Crudo, Buñuelos, Anchoas, Gildas, Sardinas, Pepa en Adobo are fin fish"},
{cat:"Allergens & Mods",q:"Egg-free tapas options?",a:"Pimientos de Padrón, Setas, Gambas, Pintxos Morunos, Pulpo, Berenjena Frita, Dátiles, Escalivada",x:"Bravas without egg still has egg in the aioli — brava-only, aioli off"},
{cat:"Allergens & Mods",q:"Vegan-friendly path through the menu?",a:"Encurtidos, Pan a la Catalana, Padrón, Primavera paella (+ Ajo Blanco no jamón)",x:"Confirm no aioli / dairy at fire with Chef"},
{cat:"Allergens & Mods",q:"Setas — mods?",a:"Ají verde on the side; quinoa on the side",x:"Shoyu = soy & wheat"},
{cat:"Allergens & Mods",q:"Pulpo a la Gallega — mods?",a:"No paprika; no saffron potatoes",x:"Dairy lives in the potatoes"},
{cat:"Allergens & Mods",q:"What utensil drops with any paella?",a:"Cuchara de paella",x:""},
{cat:"Allergens & Mods",q:"Gambas — what's the gluten?",a:"The baguette it's served with — leave it off for a GF guest",x:"Prawns, garlic, árbol chili, olive oil are all GF"},
{cat:"Allergens & Mods",q:"Where does dairy hide in the desserts?",a:"Every dessert has dairy — including Tarta de Santiago (vanilla ice cream) and Goxua (mascarpone)",x:"Santiago without the ice cream is the only DF option"},
];
