// ---- Coach: quiz hints + "remember it" lines, written against the Aventura menu ----
// Audience: new staff with no restaurant background (often students). Every hint is a nudge in
// plain words — a Spanish word clue, how a glass is used, where an allergen hides — never the answer.
// "hook" is the one line to remember, shown after the question is answered.
// Keys must match the item names in food.js / drinks.js / guide.js exactly.
const COACH = {};

// ---------- FOOD ----------
// id: "which dish is this?" · mods / ut / pair: only where that question can be asked
COACH.food = {
"Encurtidos":{id:"Spanish clue: the name just means “pickles.”",hook:"Encurtidos = pickles: mixed Spanish olives and house-pickled veg. Vegan, GF and DF — the safest first plate for any table.",ut:"Loose olives and pickles: something to scoop with, plus a little dish on the side."},
"Quesos":{id:"Spanish clue: the name is simply the plural of “cheese.”",hook:"Quesos = cheeses: a board of three Spanish cheeses with pickles, jam and bread. Always name every cheese.",mods:"Boards are the most flexible thing on the menu. Almost anything can change, with one safety rule for cheese swaps.",ut:"There's jam to scoop and cheese to cut."},
"Sardinas":{id:"Spanish clue: say the name out loud — it sounds almost exactly like the English fish.",hook:"Sardinas = tinned Spanish sardines with green salsa verde, piparra peppers and house-made chips.",mods:"The chips can be swapped for the bread used on other plates, and the green sauce can move.",ut:"Tinned fish and sauce: something small to scoop, something to cut."},
"Anchoas con Piperrada":{id:"Spanish clue: “anchoas” = anchovies; “piperrada” is a Basque pepper-and-tomato stew.",hook:"Anchoas = white and brown anchovies on grilled bread with piperrada, a Basque pepper-tomato stew."},
"Escalivada":{id:"Clue: a Catalan word for vegetables roasted over hot embers.",hook:"Escalivada = smoky Catalan roasted eggplant, peppers and onion with bread. Printed V — ask Chef before promising vegan, DF or GF.",mods:"Only one part of this plate has gluten, and it can be served separately.",ut:"Soft roasted vegetables to portion out and spread."},
"Ajo Blanco":{id:"Spanish clue: the name means “white garlic.” It's a chilled soup.",hook:"Ajo Blanco = “white garlic”: a cold almond soup from Andalusia, topped with green grapes and shaved jamón.",mods:"Only one topping keeps this from being vegetarian.",ut:"It's a soup."},
"Quesos y Charcutería":{id:"Spanish clue: “cheeses and cured meats.” It's the big board.",hook:"The big board: three cheeses + three cured meats (jamón, lomo, chorizo), pickles, jam and bread. Name everything on it.",mods:"Same flexibility as the cheese board, plus one extra rule for which meats can be swapped in.",ut:"There's jam to scoop and meat and cheese to cut."},
"Pan a la Catalana":{id:"Spanish clue: “bread, Catalan style.” Grilled bread rubbed with tomato.",hook:"Pan a la Catalana = grilled bread rubbed with garlic and fresh tomato, olive oil and salt. Vegan. $8 at happy hour.",mods:"It's vegan as-is, but a guest can add a topping — the cured ham or the white anchovies used elsewhere on the menu."},
"Almendras y Piña":{id:"Spanish clue: “almonds and pineapple.”",hook:"Almendras y Piña = almonds and pineapple: brûléed pineapple on goat cheese–almond spread on toast. $3 each at happy hour."},
"Crudo de Atún":{id:"Spanish clue: “crudo” = raw, “atún” = tuna.",hook:"Crudo de Atún = raw bluefin tuna in a watermelon agua chile. It's raw — always mention that.",ut:"Delicate raw fish in a sauce — just one piece of silverware."},
"Tortilla Española":{id:"Spanish clue: in Spain a “tortilla” is a potato-and-egg omelet, not a flatbread.",hook:"Tortilla Española = Spanish omelet of potato, onion and eggs, with brava sauce and garlic alioli.",mods:"Two sauces come on it and either can move — plus there's one add-on from the cured-meat world.",ut:"It comes as a thick wedge that needs cutting."},
"Patatas Bravas":{id:"Spanish clue: “patatas” = potatoes; “bravas” = fierce, for the spicy sauce.",hook:"Patatas Bravas = crispy potatoes with spicy brava sauce and garlic aioli. Our #1 seller; $8 at happy hour.",mods:"Either sauce can move to the side, and there's a breakfast-style add-on.",ut:"Bite-size potatoes in sauce — one simple utensil to share."},
"Dátiles con Chorizo":{id:"Spanish clue: “dátiles” = dates.",hook:"Dátiles = dates stuffed with chorizo, wrapped in bacon, over Dijon membrillo (quince paste). GF and DF; $3 each at happy hour."},
"Pimientos de Padrón":{id:"Spanish clue: “pimientos” = peppers; Padrón is the town in Galicia they come from.",hook:"Pimientos de Padrón = blistered little green peppers with smoked salt and lemon. “Spanish roulette” — about one in ten is hot. Vegan."},
"Berenjena Frita":{id:"Spanish clue: “berenjena” = eggplant, “frita” = fried.",hook:"Berenjena Frita = crispy fried eggplant with chili-honey and crumbled blue cheese. Fried, so it's in the shared fryer.",mods:"One topping is the only thing keeping it from being dairy-free.",ut:"It's a shareable pile — guests serve themselves from it."},
"Setas":{id:"Spanish clue: it's the Spanish word for mushrooms.",hook:"Setas = mushrooms: grilled king trumpet with shoyu, ají verde and puffed quinoa. Shoyu = soy + wheat, so it's not gluten-free.",mods:"Two toppings can move to the side: a green sauce and a crunchy grain.",ut:"Something to scoop the sauce with."},
"Croquetas de Setas y Trufa":{id:"Spanish clue: “setas” = mushrooms, “trufa” = truffle.",hook:"Mushroom and black-truffle croquetas: creamy béchamel inside, crispy outside, on truffle mayo. $2 each at happy hour.",mods:"The sauce underneath is the only thing that can move."},
"Croquetas de Jamón":{id:"Spanish clue: “jamón” = Spain's cured ham.",hook:"Jamón croquetas with hazelnut romesco. Heads up: the romesco means tree nuts. $2 each at happy hour.",mods:"The nut sauce can go on the side, or be swapped for the sweet fruit paste served with another croqueta."},
"Croquetas de Manchego":{id:"Spanish clue: manchego is Spain's famous sheep's-milk cheese.",hook:"Manchego croquetas with quince paste — the vegetarian croqueta. $2 each at happy hour.",mods:"The sweet fruit paste on the side is the only thing that can move."},
"Gambas":{id:"Spanish clue: look for the Spanish word for prawns / shrimp.",hook:"Gambas = prawns sizzled in garlic and árbol chili, with bread to soak up the oil. Shellfish — and the bread is the only gluten.",mods:"The only gluten on the plate can be left off.",ut:"Prawns to spear, garlicky oil to spoon up."},
"Pulpo a la Gallega":{id:"Spanish clue: “pulpo” = octopus; “a la gallega” = Galician style.",hook:"Pulpo a la Gallega = Galician-style octopus with sweet paprika over saffron potatoes. Octopus is a mollusk; the dairy is in the potatoes.",mods:"Guests can lose the red spice on top or the potatoes underneath.",ut:"Octopus needs cutting."},
"Pepa en Adobo":{id:"Spanish clue: “adobo” is a garlic–paprika–vinegar marinade. This is the fried fish.",hook:"Pepa en Adobo = swordfish marinated in adobo, fried crisp, with lemon aioli. Say swordfish (it used to be mahi).",mods:"The one sauce can go on the side.",ut:"Crispy pieces of fish — one utensil."},
"Pluma Katsu":{id:"Clue: “katsu” is Japanese for a breaded, fried cutlet; “pluma” is a cut of Ibérico pork.",hook:"Pluma Katsu = panko-fried Ibérico pork with sherry tonkatsu sauce and slaw. Hidden risk: anchovy (Worcestershire) in the sauce.",mods:"Only one change is allowed, and it's about the sauce.",ut:"A breaded pork cutlet that needs cutting."},
"Flor de Alcachofa":{id:"Spanish clue: “alcachofa” = artichoke; “flor” = flower.",hook:"Flor de Alcachofa = grilled artichoke with cured egg yolk and anchovy aioli. Not vegetarian unless you sub the garlic aioli.",mods:"The aioli is what changes: moved to the side, or swapped for a version with no fish.",ut:"A whole grilled artichoke to cut and eat."},
"Pintxos Morunos":{id:"Clue: “pintxos” are Basque small bites; “morunos” means Moorish-spiced. This is the steak.",hook:"Pintxos Morunos = spiced grilled skirt steak with roasted beets, tomatillo salsa and spicy greens. $3 a piece at happy hour.",mods:"It's about how the kitchen prepares the meat for one kind of allergy.",ut:"It's steak."},
"Buñuelos de Bacalao":{id:"Spanish clue: “buñuelos” = fritters; “bacalao” = salt cod.",hook:"Buñuelos de Bacalao = crispy salt-cod fritters with piquillo-pepper cream for dipping. $3 each at happy hour."},
"Marinera Fideuà":{id:"Clue: a fideuà is paella made with short toasted noodles instead of rice; “marinera” = seafood style.",hook:"Marinera Fideuà = seafood “paella” made with toasted fideo noodles instead of rice — crab and shrimp. Noodles = wheat, so NOT gluten-free.",mods:"The garlic sauce is the only thing that changes.",ut:"Every paella gets the same special serving spoon."},
"Rabo de Toro":{id:"Spanish clue: the name literally means “bull's tail” — that's oxtail.",hook:"Rabo de Toro = paella with red-wine-braised oxtail and piparra peppers. GF and DF.",mods:"The pickled pepper can go on the side.",ut:"Every paella gets the same special serving spoon."},
"Americana":{id:"Clue: our house paella and the cheapest one ($50) — chicken, sausage and chorizo.",hook:"Americana = our house paella: chicken thigh, Catalan sausage and chorizo with cauliflower, romano beans and broccolini. $50; GF and DF.",ut:"Every paella gets the same special serving spoon."},
"Señorito":{id:"Clue: the name means “little gentleman” — the seafood arrives already peeled.",hook:"Señorito = seafood paella (whitefish, calamari, prawns), all peeled and ready to eat — no work for the “little gentleman.” GF and DF.",mods:"The garlic sauce is the only thing that changes.",ut:"Every paella gets the same special serving spoon."},
"Valenciana":{id:"Clue: named for Valencia, the city where paella was born — the original.",hook:"Valenciana = the original paella from Valencia: chicken, romano and white beans, artichoke, rosemary and saffron. GF and DF.",ut:"Every paella gets the same special serving spoon."},
"Primavera":{id:"Spanish clue: the name means “spring” — think vegetables.",hook:"Primavera = the vegetable paella — vegan, GF and DF. Confirm the pesto with Chef before promising it.",ut:"Every paella gets the same special serving spoon."},
"AvenChurros":{id:"Clue: our own name (Aventura + …) for Spain's famous fried-dough dessert.",hook:"AvenChurros = our churros: cinnamon sugar, with caramel and chocolate sauce for dipping. Top dessert — offer the PX sherry or a Carajillo.",pair:"Fried dough and chocolate love the sweetest, most raisin-like sherry."},
"Tarta de Queso":{id:"Spanish clue: the name literally means “cheese tart.”",hook:"Tarta de Queso = Basque “burnt” cheesecake — dark and caramelized on top, creamy inside.",pair:"A cream sherry: dried fruit and nutty notes against rich, creamy cheese.",ut:"A slice of cheesecake — one utensil."},
"Goxua":{id:"Clue: a Basque layered dessert — passion fruit curd, sponge cake and mascarpone.",hook:"Goxua = Basque trifle: passion fruit curd, cake and mascarpone. Contains pork gelatin, so it's NOT vegetarian.",pair:"A golden, honeyed, floral dessert wine to match the passion fruit.",ut:"Soft and layered — you'd scoop it."},
"Torrijas":{id:"Clue: Spain's version of French toast.",hook:"Torrijas = Spanish French toast: rum-soaked brioche, brûléed, with strawberries and vanilla mascarpone.",pair:"The same style as the cheesecake's pairing — a nutty, dried-fruit cream sherry.",ut:"Soft brioche — one utensil does it."},
"Tarta de Santiago":{mods:"The cake itself is dairy-free. Only one thing on the plate isn't.",id:"Clue: named for Santiago de Compostela in Galicia — an almond cake.",hook:"Tarta de Santiago = Galician almond cake with vanilla ice cream. Our gluten-free dessert — but it has nuts, and dairy in the ice cream.",pair:"Not a sherry — a medium-sweet wine from a Portuguese island.",ut:"Cake plus ice cream — two utensils."},
"Bizcocho de Chocolate y Pistacho":{id:"Spanish clue: “bizcocho” = cake, “chocolate y pistacho” = chocolate and pistachio.",hook:"Bizcocho = milk-chocolate olive-oil brownie with pistachio and sea salt. Pistachio = tree nut.",pair:"Not a sherry — a gentle Italian wine-based aperitivo.",ut:"One utensil — the dessert kind."},
"Gildas Tradicional":{id:"Clue: the classic Basque pintxo on a skewer — anchovy, pepper, pickle and olive in one bite.",hook:"Gilda = the original Basque skewer: white anchovy, piparra pepper, cornichon and olive. $2, happy hour only."},
"Jamón y Manchego":{id:"Spanish clue: cured ham and Spain's sheep's-milk cheese.",hook:"Jamón y Manchego = ham, manchego and quince on toast. $3 bite, happy hour only."},
"Papas Fritas y Jamón":{id:"Spanish clue: “papas fritas” = chips / fries — plus cured ham.",hook:"Papas Fritas y Jamón = house-seasoned chips with Fermín jamón serrano. $10, happy hour only."},
"Churritos y Chocolate":{id:"Spanish clue: “-itos” means little — little churros.",hook:"Churritos = mini churros with chocolate sauce. $6, happy hour only (the dinner version is AvenChurros)."},
};

// ---------- DRINKS ----------
// id: from the menu description · glass / garnish / build / tape: per question type
COACH.drink = {
"Mare Nostrum":{id:"Name clue: Latin for “our sea” — the Mediterranean.",hook:"Mare Nostrum = “our sea”: Oaxacan rum, Strega and Montenegro, served up in a Nick & Nora with a dried lime.",glass:"All spirits and liqueurs, no soda, no ice in the glass — the small stemmed glass for strong drinks.",garnish:"Lime is all over this spec (fresh juice and lime-leaf bitters). The garnish is a dried slice of it.",build:"Batch, a small splash of fresh citrus, then foam and bitters by the dash.",tape:"Memory trick: one color — picture the Mediterranean sun."},
"La Huerta":{id:"Name clue: the Spanish name means “the orchard.” Think apples.",hook:"La Huerta = “the orchard”: applejack, Drambuie, fernet and cinnamon, in a coupe with a maple-sugar rim.",glass:"Shaken with citrus and foam, served up (no ice) — the wide, shallow stemmed glass.",garnish:"No fruit on this one. Look at the sweetener in the spec — it goes on the edge of the glass.",build:"Batch, a generous pour of lemon (not lime), then foam.",tape:"Memory trick: picture an apple — the skin and the inside."},
"Pasión Ciega":{id:"Name clue: “pasión” — as in passion fruit.",hook:"Pasión Ciega = “blind passion”: reposado tequila, passion fruit and elote liqueur over a king cube.",glass:"Served on the rocks — one big clear cube — in the short, heavy glass.",garnish:"Two garnishes: a leaf that goes with lime, and a dried slice of the fruit in the cordial.",build:"A 3 oz batch plus a half-ounce of just one fresh citrus.",tape:"Memory trick: the color of the leaf on top, plus what you see with your eyes closed (“blind”)."},
"El Arbol de Guernica":{id:"Name clue: “the tree of Guernica” — a symbol of the Basque Country.",hook:"El Árbol = “the tree”: cachaça, Averna and orange brandy with orange and lime, dumped into a Collins with mint.",glass:"It gets “dumped” — poured straight in with its ice — into the tall, skinny glass.",garnish:"A tree needs something green and leafy. Think herb.",build:"Batch, then two fresh juices at a half-ounce each.",tape:"Memory trick: what color is a tree?"},
"El Intercambio":{id:"Name clue: “the exchange” — Spain's red-wine-and-cola classic (the kalimotxo).",hook:"El Intercambio = our kalimotxo: vanilla-infused garnacha (red wine) topped with cola, with a half orange wheel.",glass:"Topped with cola, it's a long drink — the tall glass.",garnish:"Half of a citrus wheel — the fruit that goes with cola and vanilla.",build:"Just two steps: the wine from a squeeze bottle, then a soda on top.",tape:"Memory trick: what color is cola?"},
"La Abeja Sonriente":{id:"Name clue: “the smiling bee” — so, honey.",hook:"La Abeja Sonriente = “the smiling bee”: Priorat vermut, honey, lemon and soda in a Collins.",glass:"Topped with soda, it's a long drink — the tall glass.",garnish:"Match the citrus in the spec — dried.",build:"Batch, a splash of fresh citrus, then top with soda.",tape:"Memory trick: what colors is a bee?"},
"Carajillo":{id:"Name clue: Spain's classic coffee-and-liqueur drink.",hook:"Carajillo = Spain's coffee cocktail: elote mezcal, Licor 43 and fresh espresso over a king cube, with dried orange and flaky salt.",glass:"Over one big ice cube, in the short, heavy glass.",garnish:"The spec lists orange and Maldon (flaky sea salt). Both end up on top.",build:"Batch, plus a full shot of something from the coffee machine.",tape:"Memory trick: the color of the garnish, plus golden Licor 43."},
"Sinfonía Agridulce":{id:"Name clue: “bittersweet symphony” — tomato gin and Campari with tonic.",hook:"Sinfonía Agridulce = “bittersweet symphony”: tomato gin, Campari and orange with tonic, in a goblet.",glass:"It's a gin tonic — they all go in the big round-bowled glass.",garnish:"Two garnishes: the pepper in the spec, plus a dried slice of the citrus.",build:"Like every gin tonic here: a 2 oz batch, then top with tonic.",tape:"Memory trick: what color are tomatoes and Campari?"},
"Sangre y Semilla":{id:"Name clue: “blood and seed” — think blood orange.",hook:"Sangre y Semilla = “blood and seed”: Mahón gin and blood-orange liqueur with tonic and a rosemary sprig.",glass:"It's a gin tonic — the big round-bowled glass.",garnish:"It's the herb named in the spec.",build:"The gin tonic formula: 2 oz batch, top with tonic.",tape:"Memory trick: look at the citrus liqueur in the spec. What color is that fruit's peel?"},
"Orden del Médico":{id:"Name clue: “doctor's orders” — tonic water started out as medicine.",hook:"Orden del Médico = “doctor's orders”: Citadelle (our house gin), Italicus bergamot and tonic, with juniper, cucumber and mint.",glass:"It's a gin tonic — the big round-bowled glass.",garnish:"Three garnishes: the berry that flavors gin, the cool green veggie in the spec, and an herb.",build:"The gin tonic formula: 2 oz batch, top with tonic.",tape:"Memory trick: picture the color of a doctor's scrubs."},
"Tinta":{id:"Name clue: the name means “ink” — it's the dark red sangria.",hook:"Tinta = the red sangria: garnacha with pomegranate, orange, allspice, brandy and Gran Gala. Our traditional one.",glass:"Sangria by the glass shares a glass with the gin tonics — or comes as a pitcher."},
"Soleado":{id:"Name clue: the name means “sunny” — it's the white-wine sangria.",hook:"Soleado = “sunny”: the white sangria with Viura, Aperol, wild strawberry and lemon.",glass:"Sangria by the glass shares a glass with the gin tonics — or comes as a pitcher."},
"El Parque":{id:"Name clue: “the park” — a fizzy, tangy alcohol-free drink.",hook:"El Parque = “the park”: alcohol-free — fruit-and-pineapple shrub, ginger, citrus and soda in a tulip.",glass:"It's alcohol-free. Our NA drinks use the curvy glass that narrows at the top.",garnish:"A dried citrus slice plus something pretty from a garden.",build:"No batch here: a shrub (a tangy drinking vinegar), pineapple, then soda."},
"Sueños de Suerte":{id:"Name clue: “dreams of luck” — an Aperol-style drink with no alcohol.",hook:"Sueños de Suerte = “dreams of luck”: NA bitter citrus, spiced orange and lime, served up in a coupe.",glass:"Shaken and served up with foam, like La Huerta — the wide, shallow stemmed glass.",garnish:"A dried wheel of the fresh citrus in the spec.",build:"Three equal 1.5 oz pours, plus foam."},
"Dama Rosa":{id:"Name clue: “pink lady” — pink NA gin with tonic.",hook:"Dama Rosa = “pink lady”: Lyre's pink NA gin and tonic with grapefruit and lime — our alcohol-free gin tonic.",glass:"It's alcohol-free, so it goes in the NA glass — curvy, narrowing at the top.",garnish:"Same idea as a real gin tonic: the gin berry, plus a cool green veggie and an herb.",build:"NA gin, two citrus juices, then top with tonic."},
};

// ---------- WINES ----------
// g: the grape in plain words · hook: the one-line story
COACH.wine = {
"Cava Torremilanos Peñalba López, Brut Nature":{g:"cava (Spanish sparkling)",hook:"Bone-dry sparkling (“Brut Nature” = no sugar added). A rare cava made outside Catalonia, in Ribera del Duero. Like Champagne."},
"Rosé Cava Portell, Brut":{g:"rosé cava",hook:"Pink bubbles from Penedès — rhubarb, wild strawberry, blood orange. Like rosé Champagne."},
"Macabeo Tardano":{g:"Macabeo",hook:"Macabeo is the main cava grape, made here as a still, dry white — orchard fruit, citrus, fennel. Like Pinot Grigio."},
"Albarín Blanco Pardevalles":{g:"Albarín Blanco (not Albariño!)",hook:"Albarín Blanco — a rare grape from León. Don't mix it up with Albariño! Elderflower, lemongrass, pear."},
"Albariño Jorge Ordóñez 'La Caña'":{g:"Albariño",hook:"Albariño from Rías Baixas on the Atlantic coast — peach, apricot, Meyer lemon. Seafood's best friend."},
"Malvasía Blend Bodegas Almaroja 'Pirita Blanco'":{g:"Malvasía blend",hook:"Biodynamic Malvasía blend from the Portuguese border — “pirita” is the fool's gold in the soil. Floral, mineral, honeyed."},
"Viura Blend Ostatu":{g:"Viura",hook:"White Rioja (mostly Viura) from a family that's grown grapes for 250+ years — quince, lemon zest, limestone. Like Pinot Grigio."},
"Sumoll / Xarel·lo Can Sumoi 'La Rosa'":{g:"Sumoll and Xarel·lo",hook:"A natural rosé from the Penedès mountains — strawberry, basil, kiwi. Like a Provence rosé with more texture."},
"Hondarrabi Beltza Ameztoi 'Stimatum'":{g:"Hondarrabi Beltza",hook:"A RED txakoli from the Basque coast — light, served chilled, a little spritzy. Like Beaujolais."},
"Mencía Merayo 'Las Tres Filas'":{g:"Mencía",hook:"Mencía from Bierzo in northwest Spain — fresh red berries, silky, no oak. Like Pinot Noir."},
"Callet Blend Mesquida Mora 'Sincronía Negre'":{g:"Callet and Manto Negro",hook:"An island red from Mallorca's native grapes, made fresh and juicy. Like Grenache."},
"Cariñena Alemany i Corrió 'El Microscopi'":{g:"Cariñena (Carignan)",hook:"Old-vine Cariñena from a tiny Penedès cellar — dark berries, herbs and spice. Our priciest glass."},
"Tempranillo Volver Tinto":{g:"Tempranillo",hook:"Tempranillo — but from La Mancha, NOT Rioja. Black currant, plum and a little toast from oak."},
"Monastrell Bodegas Carchelo 'C'":{g:"Monastrell",hook:"Monastrell from Jumilla — blackberry, blueberry, violet. Ripe and easy, like Zinfandel."},
"César Florido 'Moscatel Dorado'":{g:"Moscatel",hook:"Golden Moscatel from the sherry region — orange blossom and honey. Pairs with the Goxua."},
"Lustau 'East India Solera' Cream Sherry":{g:"Oloroso sweetened with PX",hook:"Cream sherry — dried fruit, cocoa, walnut. Pairs with the Tarta de Queso and Torrijas."},
"Lustau 'San Emilio' Pedro Ximénez":{g:"Pedro Ximénez (PX)",hook:"PX: the sweetest sherry, from sun-dried grapes — raisin, fig, chocolate. Pairs with the AvenChurros."},
"Rare Wine Co 'Boston Bual' Madeira":{g:"Bual (Madeira)",hook:"Medium-sweet Madeira — date, walnut, toffee. An open bottle lasts for months. Pairs with the Tarta de Santiago."},
"Rare Wine Co 'New York Malmsey' Madeira":{g:"Malmsey (Madeira)",hook:"The sweetest style of Madeira — candied nuts, dark caramel, baking spice."},
};

// ---------- GUIDE / ALLERGEN FACT CARDS (keyed by the question) ----------
COACH.fact = {
"House vodka?":"It's the Texas vodka most guests already know — made from corn in Austin.",
"House gin?":"It's French, from Cognac, with 19 botanicals — the same gin that's in the Orden del Médico.",
"House rum?":"From Nicaragua. The name means “flower of the cane.”",
"House tequila?":"An unaged (blanco) tequila — the name sounds like the English word “exotic.”",
"House mezcal?":"A smoky Espadín mezcal from San Miguel Ejutla.",
"House bourbon?":"The Kentucky bourbon with red wax dripping down the neck of the bottle.",
"House rye?":"A Pennsylvania rye that shares its name with a famous Philadelphia square.",
"Standard pour size?":"One standard US shot. (Dessert wines pour bigger.)",
"A guest orders it \"up\" — that means?":"Picture a classic martini.",
"\"Neat\" means?":"Picture whiskey poured straight from the bottle into a glass, nothing else.",
"\"Dirty\" means?":"Think dirty martini — cloudy from something salty out of a jar.",
"A \"perfect\" Manhattan uses?":"“Perfect” = perfectly balanced between two kinds of one ingredient.",
"\"Double\" means?":"Count the shots.",
"\"Tall\" vs \"short\"?":"Same amount of alcohol either way — what changes is the glass and how much mixer.",
"The coupe is used for?":"La Huerta and Sueños de Suerte go in it — both shaken and served with no ice.",
"The rocks glass is used for?":"Pasión Ciega and the Carajillo go in it — over one big cube.",
"The neat glass is used for?":"The smallest glass on the bar, for one quick sip.",
"The champagne flute is used for?":"Tall and thin to keep bubbles going — both cavas go here.",
"The Nick & Nora is used for?":"Mare Nostrum goes in it: small, stemmed, for strong drinks with no mixer.",
"The tulip glass is used for?":"El Parque and Dama Rosa go in it — think alcohol-free.",
"The goblet is used for?":"Big round bowl on a stem: the drinks topped with tonic, plus one wine punch.",
"The Collins glass holds?":"Tall and skinny. El Árbol, El Intercambio and La Abeja Sonriente go in it — plus plenty of non-cocktails.",
"The wine glass (bar side) is for?":"Two fizzy things that aren't wine by the glass.",
"The white wine glass is used for?":"It's for a drink that comes out in a pitcher.",
"The 'AP' glass is used for?":"AP = all purpose. Which drinks does one standard glass cover?",
"How long does a paella take?":"Every paella is cooked from scratch when it's ordered, so it takes a while. Tell guests when they order, not when they ask.",
"How many people does a paella feed?":"It's printed on the menu: a pan for sharing, not one person's plate.",
"Sunday paella deal?":"Printed on the dinner menu (“Like a Spaniard”) — Sunday is paella day.",
"The surcharge on every bill?":"A small percentage, printed on the menu, to offset rising costs.",
"Menu diet codes?":"The menu uses four codes. Watch out: V and VG mean different things.",
"How big is a dessert-wine pour?":"Bigger than a shot, smaller than a glass of table wine.",
"Three menus in service right now?":"Dinner, dessert, and the early/late deal menu — each has its own print date.",
"Happy hour hours?":"Two windows: late afternoon, and late night until close.",
"Happy hour drink deal?":"One simple percentage off, and it covers every drink.",
"The $2 bites (Bocados)?":"The anchovy skewer plus the three croquetas.",
"The $3 bites (Clásicos)?":"Per-piece versions of some tapas — dates, cod fritters, pineapple toast, steak — plus a ham-and-cheese toast.",
"Happy hour 'Para Compartir' plates?":"Five shareable plates. Several are cheaper versions of dinner tapas; a couple only exist at happy hour.",
"Happy hour price vs dinner price — Patatas Bravas?":"Happy hour saves the guest about $2.",
"What is 'Jamón y Manchego'?":"Name clue: cured ham + sheep's-milk cheese. It's a happy hour bite.",
"What are 'Churritos y Chocolate'?":"“-itos” means little. Happy hour only.",
"Papas Fritas y Jamón?":"“Papas fritas” = chips. Happy hour only.",
"The defining botanical of gin?":"It's the berry garnish on the Orden del Médico and the Dama Rosa.",
"Tequila must be made from?":"One specific plant, grown only in certain parts of Mexico.",
"Blanco means?":"“Blanco” = white. Think clear, fresh from the still.",
"Reposado means?":"“Reposado” = rested — a short nap in a barrel.",
"Añejo means?":"“Añejo” = aged — longer in the barrel than a reposado.",
"Bourbon rules?":"Three rules: where it's made, its main grain (think cornbread), and a brand-new barrel.",
"Rye whiskey rules?":"Same idea as bourbon, but a different main grain — and it tastes spicier.",
"Scotch rules?":"Made in one country, with a minimum age of a few years.",
"Brandy is distilled from?":"Brandy is to wine what whiskey is to beer.",
"Orujo is?":"Made from what's left after grapes are pressed (skins and seeds), in Spain's north.",
"Licor de Hierbas is?":"“Hierbas” = herbs.",
"Amaro is?":"Italian and herbal. The name tells you how it tastes.",
"Rum & cachaça are distilled from?":"Both come from the same tall grass that sugar is made from.",
"Terroir means?":"From the French “terre,” earth: everything about the place a grape grows.",
"Vintage means?":"It's the year on the label — but the year of what?",
"US varietal labeling rule?":"A US label can name one grape if a big majority of the wine is that grape — more than “most,” less than all.",
"Appellation means?":"Rioja and Napa Valley are examples: a place name with legal protection.",
"Tannin is?":"Think of over-steeped black tea — that drying feeling on your gums.",
"Acidity in wine feels like?":"What makes your mouth water — like biting a green apple.",
"Body means?":"Skim milk vs whole milk.",
"Minerality describes?":"Wet stone, chalk, a little salty — flavors that aren't fruit.",
"Finish means?":"It's about what happens after the sip is gone.",
"Old World style?":"The traditional wine countries — the continent Spain is on.",
"New World style?":"The wine countries outside Europe. Think riper and fruitier.",
"Spicy food pairs with?":"What cools spice down? Think honey on hot wings.",
"Tannic reds are best balanced with?":"Why does steak taste great with red wine? Think marbling.",
"Match the wine with the ____, not the meat.":"Chicken in cream and chicken in tomato need different wines. What changed?",
"Txakolina (chacolí) is?":"Basque, light, tangy and a little fizzy — ours is the red Ameztoi.",
"Cava is made how?":"Made the same way as Champagne — the bubbles form inside the bottle.",
"Fino / Manzanilla?":"The palest, driest sherries, aged under a layer of yeast called flor. Serve cold.",
"Amontillado?":"It starts life as a Fino, then the yeast layer fades.",
"Palo Cortado?":"The rare “happy accident” sherry — the yeast layer dies off unexpectedly.",
"Oloroso?":"It never gets the yeast layer, so it goes darker and fuller. Sip it like a fine bourbon.",
"Pedro Ximénez (PX)?":"Made from grapes dried in the sun like raisins. Pairs with our churros.",
"Cream sherry?":"A dry, nutty sherry sweetened with the raisin-y one. Ours is the East India Solera.",
"The Sherry Triangle?":"Three towns in Andalusia, Spain — the best known is Jerez.",
"Vermouth must be at least?":"It's mostly wine, plus botanicals. How much wine, at minimum?",
"Sherry ABV range?":"Stronger than table wine because it's fortified — somewhere between wine and a liqueur.",
"Madeira is?":"From a Portuguese island. It's heated on purpose, so it barely spoils.",
"Cardamaro is?":"An Italian aperitivo made from wine and thistle — it's the Bizcocho's pairing.",
"Our exclusive house beer?":"Brewed in Ann Arbor just for The Pulpo Group. Its name is a short word for eight.",
"The hazy IPA?":"Same Ann Arbor brewery as our house beer.",
"The Spanish lager?":"It's from Galicia, and the name means “star.”",
"Our NA beers?":"From a New York brewery — one light and crisp, one hoppy. Served in the tulip.",
"The cider?":"Basque cider — the same brand that goes into the Dijon membrillo on the dátiles.",
"The non-alcoholic cider?":"From Asturias, Spain's cider country. Bottle only.",
"Our water?":"Mineral water filtered through volcanic rock in Catalonia.",
"Our soda?":"Made in Detroit, from Leonard's Syrups.",
"Our tea?":"An organic tea company from right here in Ann Arbor.",
"Our coffee?":"A local Ann Arbor roaster — the name sounds like a kangaroo.",
"Butterfly pea flower party trick?":"It's a color trick: add citrus and watch.",
"NA options that aren't mocktails?":"Think beyond cocktails: beer, cider, tea, coffee and water all have alcohol-free picks.",
"Fully vegan dishes as printed (VG)?":"Vegan = no animal products at all. Look for plates with no aioli, cheese, egg or meat. One of them is a paella.",
"Vegetarian traps on the menu?":"Look for hidden fish in a sauce, pork gelatin in a dessert, and meat on a board.",
"Gluten-free paellas?":"Every rice paella is GF. The one made with noodles isn't.",
"Dairy-free tapas as printed (DF)?":"Aioli is egg + oil, not dairy. Look for tapas without cheese, cream or butter.",
"Gluten-free desserts?":"One is an almond cake. The other uses GF flour in its sponge.",
"Pescatarian guest — what's off limits besides meat?":"Pescatarians eat fish but not meat. Look for pork, chicken and beef — including hidden gelatin.",
"What's in the shared fryer? (cross-contact)":"Think of everything that gets fried in the same oil: potatoes, breaded croquetas, fish, ham chips…",
"Which dessert contains pork?":"Gelatin is often made from pork. Which dessert is set with gelatin?",
"Hidden fin-fish allergen in the Pluma Katsu?":"It's in the sauce: a classic English sauce that's made with anchovies.",
"Is the Marinera Fideuà gluten-free?":"Fideo noodles are pasta. What's pasta made from?",
"Which dessert is naturally gluten-free?":"Look for a cake made with nut flour instead of wheat.",
"Guest is pregnant and orders the cheese board?":"It's about how the cheese is made, and one animal's milk. Chef confirms any swap.",
"Pintxos Morunos for a gluten-free guest?":"The ingredients are fine — the risk is cross-contact during prep. What could the kitchen do differently?",
"Which items have tree nuts?":"Look for almonds, Marcona almonds, hazelnut romesco and pistachio across the menu.",
"Which items are crustacean/shellfish?":"Shellfish = shrimp, prawns and crab. Octopus is a mollusk, not shellfish.",
"Egg-free tapas options?":"Egg hides in aioli, tortilla, croquetas and fritters. Skip those.",
"Vegan-friendly path through the menu?":"The printed VG dishes, plus one cold soup without its topping.",
"Setas — mods?":"Two toppings can move to the side: a green sauce and a crunchy grain.",
"Pulpo a la Gallega — mods?":"Guests can drop the red spice on top or the potatoes underneath.",
"What utensil drops with any paella?":"Every paella gets the same special serving spoon — it has a Spanish name.",
"Gambas — what's the gluten?":"Prawns, garlic, chili and olive oil are all gluten-free. So what's left on the plate?",
"Where does dairy hide in the desserts?":"Check each dessert for cream, butter, mascarpone or ice cream.",
};

// ---------- allergen & diet coaching (menu-specific) ----------
// Where each allergen shows up on OUR menu — used for "a guest has a ___ allergy" questions
COACH.hides = [
[/gluten|wheat/,"gluten","bread (baguette, ciabatta, crostini, brioche), anything breaded or battered, the fideo noodles and shoyu"],
[/dairy|milk/,"dairy","cheese (manchego, blue, goat, mascarpone), cream, butter, béchamel in the croquetas — and the potatoes under the Pulpo"],
[/egg/,"egg","aioli and alioli, the tortilla, croquetas and fritters, cakes and custards"],
[/crustacean|shellfish/,"shellfish","the prawns, shrimp and crab"],
[/mollusk/,"mollusk","the octopus (pulpo) and calamari"],
[/fish/,"fin fish","anchovies (and anchovy aioli), boquerones, sardines, tuna, salt cod, swordfish — and Worcestershire in the katsu sauce"],
[/nut/,"tree nut","almonds (Ajo Blanco, Marcona, the Santiago cake), hazelnut romesco and pistachio"],
[/soy/,"soy","shoyu and the katsu sauce"],
[/sesame/,"sesame","the Pluma Katsu"],
[/pork/,"pork","jamón, chorizo, bacon, lomo, Catalan sausage — and the gelatin in the Goxua"],
[/mustard|dijon/,"mustard","the Dijon membrillo under the dátiles"],
];
COACH.diet = {
V:"Vegetarian = no meat or fish. The sneaky ones here: anchovy aioli, jamón as a topping, and pork gelatin.",
VG:"Vegan = no animal products at all: no meat, fish, dairy, eggs or honey. Aioli (egg) and cheese knock out most dishes.",
GF:"Gluten-free = no wheat. Watch for bread, anything breaded, the fideo noodles and shoyu.",
DF:"Dairy-free = no cheese, cream, butter or béchamel. Aioli is egg + oil, so it doesn't count as dairy.",
};
// ingredient → allergen "triggers" for the "Allergens in ___?" hint. Only shown when the menu's
// allergen line for that dish actually lists the allergen.
COACH.triggers = [
[/baguette|ciabatta|crostini|brioche|flour/,/gluten/,"gluten"],
[/breadcrumb|panko/,/gluten/,"gluten"],
[/fideo/,/gluten/,"gluten"],
[/shoyu/,/gluten|soy/,"soy + gluten"],
[/aioli|alioli|mayo|egg yolk|eggs?\b/,/egg/,"egg"],
[/cheese|manchego|mascarpone|cream|butter|milk|béchamel/,/dairy/,"dairy"],
[/jamón|chorizo|bacon|lomo|pork|botifarra|gelatin/,/pork/,"pork"],
[/prawns?|shrimp|crab/,/crustacean|shellfish/,"shellfish"],
[/octopus|calamari/,/mollusk/,"mollusk"],
[/anchov|boquer|sardine|tuna|bacalao|swordfish|whitefish|worcestershire/,/fish/,"fin fish"],
[/almond|marcona|hazelnut|pistachio/,/nut/,"tree nuts"],
[/garlic|onion|shallot|scallion|chives?|leek/,/allium/,"allium"],
[/tomato|pepper|paprika|pimentón|potato|eggplant|chil[ie]|cayenne|espelette|piquillo|piparra|shishito/,/nightshade/,"nightshade"],
[/sofrito/,/allium|nightshade/,"allium + nightshade (onion, garlic, tomato)"],
];
COACH.allergenHint = function (f) {
  const ing = String(f.ing).toLowerCase(), all = String(f.all).toLowerCase(), seen = new Set(), out = [];
  COACH.triggers.forEach(([re, need, label]) => {
    if (seen.has(label) || !need.test(all)) return;
    if (label.startsWith("allium +") && seen.has("allium") && seen.has("nightshade")) return;
    const m = ing.match(new RegExp("(?:" + re.source + ")[a-záéíóúñ]*")); if (!m) return;
    seen.add(label); out.push(`${m[0]} → ${label}`);
  });
  let s = out.length ? "Spot the triggers: " + out.slice(0, 4).join(" · ") + "." : "Work through the ingredients one at a time.";
  if (/fryer/.test(all)) s += " Fried? Add shared-fryer cross-contact.";
  return s;
};
