const TAPE={YELLOW:"#e8c534",RED:"#c0392b",WHITE:"#f2f2f2",GREEN:"#3e7c4f",BLACK:"#111111",ORANGE:"#d97b29",BLUE:"#3a6ea5",BROWN:"#6b4423"};
const DRINKS=[
{cat:"Cócteles",name:"Mare Nostrum",price:"$17",colors:["YELLOW"],menu:"Oaxacan rum, Strega, Montenegro, citrus cordial, lime leaf bitters",glass:"Nick & Nora",build:["2.75 oz batch",".25 oz lime","2 dash Fee foam","2 dash lime leaf"],garnish:"Dehydrated lime"},
{cat:"Cócteles",name:"La Huerta",price:"$16",colors:["RED","WHITE"],menu:"Laird's applejack, Drambuie, fernet, cinnamon, Angostura bitters, maple sugar",glass:"Coupe — double strain",build:["2.7 oz batch",".75 oz lemon","2 dash Fee foam"],garnish:"Maple sugar rim"},
{cat:"Cócteles",name:"Pasión Ciega",price:"$17",colors:["GREEN","BLACK"],menu:"Espolòn reposado, Giffard passion fruit, Nixta elote liqueur, pineapple chili cordial",glass:"Rocks — king cube",build:["3 oz batch",".5 oz lime"],garnish:"Kaffir lime leaf + dehydrated piña"},
{cat:"Cócteles",name:"El Arbol de Guernica",price:"$15",colors:["GREEN"],menu:"Cachaça, Averna, orange brandy, orange, lime, demerara",glass:"Collins — dump in glass",build:["3 oz batch",".5 oz OJ",".5 oz lime"],garnish:"Mint sprig"},
{cat:"Clásicos",name:"El Intercambio",price:"$14",colors:["BROWN"],bottle:"BROWN squeeze bottle",menu:"Garnacha, vanilla bean, cola",glass:"Collins",build:["2 oz vanilla garnacha (brown squeeze bottle)","Top with cola"],garnish:"Orange ½ wheel",sell:"Kalimotxo, the Basque way — red wine & cola with a whisper of vanilla."},
{cat:"Clásicos",name:"La Abeja Sonriente",price:"$14",colors:["YELLOW","BLACK"],menu:"Priorat vermut, honey, lemon, soda",glass:"Collins",build:["2.75 oz batch",".25 oz lemon","Soda"],garnish:"Dehydrated lemon"},
{cat:"Clásicos",name:"Carajillo",price:"$18",colors:["ORANGE","YELLOW"],menu:"Vago elote mezcal, Nixta elote, Licor 43, Caffè Borghetti, espresso, orange, Maldon",glass:"Rocks — king cube",build:["2.5 oz batch","1 oz espresso"],garnish:"Dehydrated orange + salt",sell:"A spin on a classic — Nixta Elote adds a buttery, caramelized layer to a lush spiked cold brew."},
{cat:"Gin-Tonics",name:"Sinfonía Agridulce",price:"$16",colors:["RED"],menu:"Moletto tomato gin, Campari, orange, tonic, cherry pepper",glass:"Goblet",build:["2 oz batch","Tonic"],garnish:"Cherry pepper + dehydrated orange",sell:"Sweet-and-bitter — Moletto's tomato gin meets Campari and orange; savory, bright, a little spicy.",flag:"The 9/11 dinner menu prints this drink; the Sept bar-prep sheet still batches PECAS (54 oz Moletto + 27 oz Pimm's, RED tape) in this slot. Confirm the live batch and build with the bar lead before you quote it."},
{cat:"Gin-Tonics",name:"Sangre y Semilla",price:"$16",colors:["ORANGE"],menu:"Mahón Spanish gin, Solerno blood orange, tonic, rosemary sprig",glass:"Goblet",build:["2 oz batch","Tonic"],garnish:"Rosemary sprig"},
{cat:"Gin-Tonics",name:"Orden del Médico",price:"$17",colors:["BLUE"],menu:"Citadelle gin, Italicus bergamot, tonic, cucumber, juniper berries",glass:"Goblet",build:["2 oz batch","Tonic"],garnish:"Juniper, cucumber, mint"},
{cat:"Sangria",name:"Tinta",price:"14 | 54",colors:[],menu:"Pomegranate, orange, allspice, garnacha (+ VSOP brandy & Gran Gala)",glass:"Goblet — glass or pitcher",build:["Batched sangria"],garnish:"Orange quarter",sell:"Authentic & traditional — our tried-and-true."},
{cat:"Sangria",name:"Soleado",price:"14 | 54",colors:[],menu:"Viura, Aperol, crème de fraise des bois, lemon, crimson berry tisane",glass:"Goblet — glass or pitcher",build:["Batched sangria"],garnish:"Lemon wheel (confirm)"},
{cat:"Sin Alcohol",name:"El Parque",price:"$12",colors:[],menu:"Seasonal fruit & pineapple shrub, ginger, citrus",glass:"Tulip",build:["1.75 oz shrub","1 oz acid-adjusted piña","Soda"],garnish:"Dehydrated lime & flower",sell:"Tangy & effervescent — not mimicking a cocktail; for the thirst-quenching guest."},
{cat:"Sin Alcohol",name:"Sueños de Suerte",price:"$12",colors:[],menu:"Lyre's NA bitter citrus, spiced orange, lime",glass:"Coupe",build:["2 dash Fee foam","1.5 oz lime","1.5 oz spiced orange","1.5 oz NA spritz"],garnish:"Dehydrated lime wheel",sell:"Aperol-like — citrus + spice make a wonderful aperitif-style mocktail."},
{cat:"Sin Alcohol",name:"Dama Rosa",price:"$12",colors:[],menu:"Lyre's pink NA gin, tonic, lime, grapefruit, mint, juniper",glass:"Tulip",build:["2 oz Lyre's gin","1 oz grapefruit",".5 oz lime","Tonic"],garnish:"Cucumber, mint + juniper berries",sell:"An excellent gin tonica alternative — fresh, aromatic, crunchy red fruit."},
];
