const FOODILLUS={
plate:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="72" rx="92" ry="44" fill="#FBFAF9" stroke="#55565A" stroke-width="3"/><ellipse cx="110" cy="72" rx="66" ry="30" fill="none" stroke="rgba(85,86,90,0.25)" stroke-width="2"/><ellipse cx="110" cy="70" rx="40" ry="16" fill="#C67B7B" opacity=".55"/><circle cx="96" cy="66" r="8" fill="#C39A4E" stroke="#55565A" stroke-width="1.6"/><circle cx="118" cy="72" r="8" fill="#C39A4E" stroke="#55565A" stroke-width="1.6"/><circle cx="107" cy="60" r="7" fill="#D7A85A" stroke="#55565A" stroke-width="1.6"/><path d="M128 58 l6 -8 M131 58 l4 -9" stroke="#557B46" stroke-width="2.5" stroke-linecap="round"/></svg>',
cazuela:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><path d="M28 60 Q110 40 192 60 L184 96 Q110 112 36 96 Z" fill="#A85A3A" stroke="#55565A" stroke-width="3"/><ellipse cx="110" cy="60" rx="82" ry="20" fill="#F0C48A" stroke="#55565A" stroke-width="3"/><ellipse cx="110" cy="60" rx="70" ry="14" fill="#9E3B2E" opacity=".8"/><circle cx="90" cy="58" r="7" fill="#E8A75C" stroke="#55565A" stroke-width="1.5"/><circle cx="118" cy="62" r="7" fill="#E8A75C" stroke="#55565A" stroke-width="1.5"/><circle cx="134" cy="56" r="6" fill="#E8A75C" stroke="#55565A" stroke-width="1.5"/><rect x="8" y="54" width="22" height="9" rx="4" fill="#A85A3A" stroke="#55565A" stroke-width="2.5"/><rect x="190" y="54" width="22" height="9" rx="4" fill="#A85A3A" stroke="#55565A" stroke-width="2.5"/></svg>',
paella:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="72" rx="96" ry="40" fill="#B9B4A6" stroke="#55565A" stroke-width="3"/><ellipse cx="110" cy="70" rx="84" ry="32" fill="#E3A93B" stroke="#55565A" stroke-width="2"/><ellipse cx="110" cy="70" rx="84" ry="32" fill="none" stroke="#9E3B2E" stroke-width="1.5" stroke-dasharray="3 5"/><path d="M70 66 q10 -12 22 0 q-11 8 -22 0z" fill="#9E3B2E" stroke="#55565A" stroke-width="1.5"/><path d="M120 76 q10 -12 22 0 q-11 8 -22 0z" fill="#9E3B2E" stroke="#55565A" stroke-width="1.5"/><circle cx="102" cy="82" r="5" fill="#557B46" stroke="#55565A" stroke-width="1.4"/><circle cx="140" cy="62" r="5" fill="#557B46" stroke="#55565A" stroke-width="1.4"/><path d="M14 68 l-10 -6 M206 68 l10 -6" stroke="#55565A" stroke-width="4" stroke-linecap="round"/><path d="M4 62 a6 6 0 1 0 0.1 0 M216 62 a6 6 0 1 0 0.1 0" fill="#55565A"/></svg>',
board:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><rect x="22" y="36" width="176" height="72" rx="10" fill="#B98A5A" stroke="#55565A" stroke-width="3"/><rect x="34" y="46" width="152" height="52" rx="6" fill="none" stroke="rgba(85,86,90,0.2)" stroke-width="2"/><path d="M48 58 l30 0 l0 30 l-30 0z" fill="#F3E3B1" stroke="#55565A" stroke-width="1.6"/><path d="M84 54 q18 -10 36 0 q-18 12 -36 0z" fill="#B23A33" stroke="#55565A" stroke-width="1.6"/><path d="M86 74 q18 -10 36 0 q-18 12 -36 0z" fill="#B23A33" stroke="#55565A" stroke-width="1.6"/><circle cx="150" cy="66" r="14" fill="#E8862E" stroke="#55565A" stroke-width="1.6"/><circle cx="144" cy="90" r="4" fill="#557B46"/><circle cx="156" cy="92" r="4" fill="#557B46"/><circle cx="166" cy="86" r="4" fill="#557B46"/></svg>',
dessert:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="96" rx="80" ry="22" fill="#FBFAF9" stroke="#55565A" stroke-width="3"/><path d="M76 92 L84 52 L136 52 L144 92 Z" fill="#D9A15A" stroke="#55565A" stroke-width="2.5"/><path d="M84 52 L136 52 L132 60 L88 60 Z" fill="#8B5A3C"/><path d="M96 92 q8 -30 28 -40" fill="none" stroke="#6B3E2E" stroke-width="5" stroke-linecap="round"/><circle cx="150" cy="60" r="10" fill="#C67B7B" stroke="#55565A" stroke-width="1.6"/><circle cx="150" cy="60" r="4" fill="#9E3B2E"/><path d="M60 88 l-8 -14 M62 90 l-14 -6" stroke="#55565A" stroke-width="2" stroke-linecap="round"/></svg>',
bowl:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="56" rx="78" ry="20" fill="#FBFAF9" stroke="#55565A" stroke-width="3"/><path d="M32 56 Q40 112 110 116 Q180 112 188 56" fill="#FBFAF9" stroke="#55565A" stroke-width="3"/><ellipse cx="110" cy="56" rx="64" ry="13" fill="#C9C583"/><circle cx="90" cy="54" r="6" fill="#557B46" stroke="#55565A" stroke-width="1.4"/><circle cx="126" cy="58" r="6" fill="#C39A4E" stroke="#55565A" stroke-width="1.4"/><path d="M104 50 l14 4" stroke="#9E3B2E" stroke-width="3" stroke-linecap="round"/></svg>'
};
// Menus in service: Dinner 9.11.26 · Sweet Tapas 6.24.26 · Happy Hour 8.1.26
// price = dinner price · hh = happy-hour price (per piece for bites) · pair = printed dessert-wine pairing
const FOOD=[
// ---------- APERITIVO ----------
{cat:"Aperitivo",name:"Encurtidos",price:"8",ill:"bowl",drop:"Mixed Spanish olives and house-pickled vegetables.",ing:"Gordal, Verdial, Cuquillo, Zorzaleña & Cornicabra olives; pickled cauliflower, carrot, garlic (orange zest, ñora chile, rosemary, thyme); cornichons",all:"Vinegar, citrus, allium",mods:"None",ut:"Spoon, ramekin",tip:"Printed GF · VG · DF — the safest first plate for any table."},
{cat:"Aperitivo",name:"Quesos",price:"23",ill:"board",drop:"A board of three Spanish cheeses with pickles, baguette and jam.",ing:"Three Spanish cheeses (name them), tomato-pepper jam, seasonal jam, house pickles, baguette",all:"Gluten, dairy, nuts, allium",mods:"Any single item removed or on the side; cheeses can be swapped (pasteurized only, no goat's milk) — check with Chef",ut:"Small spoon (jam), knife",tip:"Always name every cheese on the board."},
{cat:"Aperitivo",name:"Sardinas",price:"24",ill:"plate",drop:"Tinned Spanish sardines with salsa verde, piparra peppers and house-made spiced potato chips.",ing:"Sardines in EVOO, Matiz piparra peppers, salsa verde (parsley, garlic, olive oil), house chips (russet, pimentón dulce & picante, espelette, tomato powder, garlic & onion powder, MSG)",all:"Fish, allium, nightshade · fryer cross-contact (chips)",mods:"Sub baguette for chips; salsa verde on the side",ut:"Small spoon, knife"},
{cat:"Aperitivo",name:"Anchoas con Piperrada",price:"14",ill:"plate",drop:"White and brown anchovies on grilled baguette with house-made piperade.",ing:"Nassari brown anchovy, Nassari white anchovy (boquerón), piperade (garlic, scallion, shallot, red bell & cubanelle pepper, tomato, sherry vinegar, espelette, bay), cava vinegar, grilled baguette",all:"Fin fish, gluten, nightshade, vinegar, alcohol, sunflower",mods:"None",ut:"None"},
{cat:"Aperitivo",name:"Escalivada",price:"16",ill:"plate",drop:"Catalan roasted vegetables — smoky marinated eggplant, peppers and onion with sea salt, served with baguette.",ing:"Roasted & marinated eggplant, red peppers, onion, olive oil, sea salt, baguette",all:"Gluten (baguette), nightshade, allium",mods:"Baguette on the side",ut:"Small spoon / knife",tip:"NEW on the 9/11 menu · printed V. Ask Chef before promising vegan, DF or GF — the ingredient list isn't in the matrix yet."},
{cat:"Aperitivo",name:"Ajo Blanco",price:"8",ill:"bowl",drop:"A traditional Andalusian chilled almond soup, topped with green grapes and fine shavings of jamón.",ing:"Almonds, olive oil, sherry vinegar, garlic, green grapes, cucumber, jamón",all:"Tree nuts (almond), allium, vinegar, pork",mods:"No jamón",ut:"Soup spoon",tip:"Printed DF · GF. Vegan/vegetarian only without the jamón."},
{cat:"Aperitivo",name:"Quesos y Charcutería",price:"33",ill:"board",drop:"Three Spanish cheeses and three cured meats with pickles, baguette and jam.",ing:"Jamón serrano, lomo serrano, chorizo, cow / sheep / goat cheese, Marcona almonds, tomato pepper jam, mixed pickles, baguette, membrillo, encurtidos",all:"Gluten, dairy, nuts, allium, pork",mods:"Any single item removed or on the side; meats & cheeses can be swapped (pasteurized only, no goat's milk, no sausage) — check with Chef",ut:"Small spoon (jam), knife",tip:"List all meats and cheeses on the board."},
{cat:"Aperitivo",name:"Pan a la Catalana",price:"11",hh:"8",ill:"plate",drop:"Garlic-rubbed grilled ciabatta with grated tomato, olive oil and sea salt.",ing:"Ciabatta, beefsteak tomato, reserva sherry vinegar, olive oil, garlic, Maldon, parsley",all:"Gluten, nightshade, allium",mods:"Add jamón serrano (+2 at happy hour); add boquerones (+2 at happy hour)",ut:"None",tip:"Printed VG · DF. $8 at happy hour."},
{cat:"Aperitivo",name:"Almendras y Piña",price:"13",hh:"3",ill:"plate",drop:"Brûléed pineapple with goat cheese and Marcona almond spread on grilled crostini.",ing:"Brûléed pineapple, goat cheese–Marcona almond spread, baguette crostini, Maldon salt, olive oil",all:"Gluten, dairy, nuts, sunflower",mods:"None",ut:"None (finger food)",tip:"$3 per piece at happy hour."},
// ---------- TAPAS ----------
{cat:"Tapas",name:"Crudo de Atún",price:"23",ill:"plate",drop:"Sushi-grade bluefin tuna in a watermelon agua chile with cucumber, ginger, shallot and serrano.",ing:"Bluefin tuna, shallot, ginger, serrano chili, cucumber, agua chile (watermelon, cilantro, cucumber, orange, lime), finger lime, olive oil, Maldon",all:"Fin fish, allium, nightshade, cilantro, citrus",mods:"None",ut:"Fork",tip:"Printed GF · DF. Served raw — mention it."},
{cat:"Tapas",name:"Tortilla Española",price:"12",ill:"plate",drop:"Spanish omelet of potato, onion and shishito peppers with salsa brava and garlic alioli.",ing:"Potato, shishito peppers, onion, eggs, salsa brava (olive oil, white vinegar, cayenne, sweet & spicy paprika, garlic, tomato paste), garlic alioli (egg yolk, canola/EVOO, white wine vinegar), chives",all:"Eggs, nightshade, allium, vinegar",mods:"Alioli on the side; brava on the side; add jamón serrano +3",ut:"Knife"},
{cat:"Tapas",name:"Patatas Bravas",price:"10",hh:"8",ill:"cazuela",drop:"Crispy fried potato with salsa brava and garlic aioli — add a fried egg if you like.",ing:"Potato, salsa brava (olive oil, white vinegar, cayenne, sweet & spicy paprika, garlic, tomato paste), garlic aioli (egg, olive oil, garlic, parsley)",all:"Nightshade, vinegar, allium, eggs · fryer cross-contact (fin fish & dairy)",mods:"Brava or aioli on the side; add fried egg +2 (also +2 jamón at happy hour)",ut:"Spoon",tip:"#1 volume item on the menu · $8 at happy hour."},
{cat:"Tapas",name:"Dátiles con Chorizo",price:"15",hh:"3",ill:"plate",drop:"Chorizo-stuffed, bacon-wrapped Medjool dates over Dijon membrillo.",ing:"Medjool dates, ground chorizo, applewood bacon, Dijon membrillo (Dijon, membrillo, Isastegi cider, cider vinegar, espelette, EVOO)",all:"Stone fruit, nightshade, vinegar, Dijon/mustard, orchard fruit, pork, allium",mods:"None",ut:"None",tip:"Printed GF · DF. $3 per piece at happy hour."},
{cat:"Tapas",name:"Pimientos de Padrón",price:"11",hh:"7",ill:"cazuela",drop:"Flash-fried shishito peppers with smoked sea salt and lemon.",ing:"Shishito peppers, lemon, smoked sea salt, smoked EVOO, parsley",all:"Nightshade, citrus · fryer cross-contact",mods:"None",ut:"None",tip:"Sell it: 'Spanish roulette — one in ten is hot.' Printed VG. $7 at happy hour."},
{cat:"Tapas",name:"Berenjena Frita",price:"17",ill:"plate",drop:"Crispy fried eggplant drizzled with chili-honey and smoked pimentón dulce, crumbled with blue cheese.",ing:"Eggplant, cornstarch, honey, chili sauce, pimentón dulce, blue cheese, chives",all:"Dairy, nightshade · fryer cross-contact (dairy, fin fish, gluten, pork, nightshade)",mods:"No blue cheese",ut:"Serving spoon"},
{cat:"Tapas",name:"Setas",price:"18",ill:"plate",drop:"Grilled mushrooms with shoyu, ají verde and puffed quinoa.",ing:"King trumpet mushroom, shoyu, ají verde, puffed quinoa",all:"Dairy, allium, soy, gluten (shoyu)",mods:"Ají verde on the side; quinoa on the side",ut:"Spoon",tip:"Printed V. Shoyu = soy AND wheat — not gluten-free."},
{cat:"Tapas",name:"Croquetas de Setas y Trufa",price:"13",hh:"2",ill:"plate",drop:"Locally cultivated mushroom and black truffle croquettes over truffle mayo.",ing:"Local mushrooms, black truffle, house béchamel, egg, breadcrumb, truffle/porcini mayo, dehydrated porcini",all:"Dairy, gluten, egg · fryer cross-contact (fin fish & dairy)",mods:"Truffle mayo on the side",ut:"None (finger food)",tip:"'Croqueta de Setas' at happy hour — $2 per piece."},
{cat:"Tapas",name:"Croquetas de Jamón",price:"13",hh:"2",ill:"plate",drop:"Serrano ham croquettes with hazelnut romesco.",ing:"Jamón serrano béchamel (manchego, butter, flour, nutmeg, milk), egg, breadcrumb, hazelnut romesco (hazelnut, tomato, sweet pepper, allium, olive oil)",all:"Pork, dairy, gluten, egg, tree nuts, nightshade · fryer cross-contact (fin fish)",mods:"Romesco on the side; sub quince",ut:"None (finger food)",tip:"$2 per piece at happy hour."},
{cat:"Tapas",name:"Croquetas de Manchego",price:"11",hh:"2",ill:"plate",drop:"Spanish-cheese béchamel croquettes with quince.",ing:"Manchego béchamel (egg, breadcrumb, manchego, butter, flour, nutmeg, milk), quince",all:"Dairy, gluten, egg, citrus · fryer cross-contact (fin fish)",mods:"Quince on the side",ut:"None (finger food)",tip:"The vegetarian croqueta · $2 per piece at happy hour."},
{cat:"Tapas",name:"Gambas",price:"21",ill:"cazuela",drop:"Prawns sizzled in garlic and árbol chili, with baguette to soak it up.",ing:"Prawns, garlic, chile de árbol, olive oil, baguette",all:"Crustacean, allium, nightshade, gluten (baguette)",mods:"No baguette",ut:"Fork / spoon"},
{cat:"Tapas",name:"Pulpo a la Gallega",price:"25",ill:"plate",drop:"The classic Galician dish — tender octopus with pimentón dulce over saffron potatoes.",ing:"Spanish octopus, pimentón dulce, saffron potatoes (butter, heavy cream), shallot-onion-garlic, chives",all:"Allium, nightshade, mollusk, dairy",mods:"No paprika; no saffron potatoes",ut:"Fork / knife",tip:"Printed GF. Dairy lives in the potatoes."},
{cat:"Tapas",name:"Pepa en Adobo",price:"18",ill:"plate",drop:"Andalusian-style fried fish — swordfish marinated in garlic, paprika and sherry vinegar, fried crisp and finished with lemon aioli and chives.",ing:"Swordfish, adobo (garlic, onion, paprika, sherry vinegar), cornstarch, lemon aioli (egg, lemon, oil), chives",all:"Fin fish, eggs, allium, nightshade, vinegar, citrus · fryer cross-contact",mods:"Aioli on the side",ut:"Fork",tip:"Was 'Mahi en Adobo' — the 9/11 menu makes it swordfish. Say swordfish."},
{cat:"Tapas",name:"Pluma Katsu",price:"21",ill:"plate",drop:"Panko-crusted pork shoulder with sherry tonkatsu sauce, napa cabbage and pickled watermelon radish.",ing:"Ibérico pork shoulder, egg, breadcrumb, slaw (napa cabbage, green onion, pickled watermelon radish, carrot), sherry tonkatsu (ketchup, soy, sugar, sherry, Worcestershire, garlic, ginger)",all:"Pork, eggs, gluten, allium, sesame, nightshade, soy, fin fish (Worcestershire in katsu sauce) · fryer cross-contact (fin fish & dairy)",mods:"Katsu sauce on the side",ut:"Fork / knife",tip:"Fin-fish allergy: the katsu sauce (Worcestershire = anchovy) is the hidden risk. Printed DF."},
{cat:"Tapas",name:"Flor de Alcachofa",price:"13",ill:"plate",drop:"Grilled artichoke with lemon and grated salt-cured egg yolk, served with anchovy aioli.",ing:"Spanish artichokes, salt-cured egg yolk, lemon, anchovy aioli (garlic, egg yolk, olive oil, brown anchovy)",all:"Allium, egg, citrus, fin fish · gluten cross-contact",mods:"Aioli on the side; sub garlic aioli",ut:"Fork / knife",tip:"Printed DF. NOT vegetarian as printed — anchovy in the aioli."},
{cat:"Tapas",name:"Pintxos Morunos",price:"24",hh:"3",ill:"plate",drop:"Grilled marinated skirt steak with roasted baby beets, tomatillo salsa and dressed spicy greens.",ing:"Skirt steak (garlic, cumin, paprika, OJ, cinnamon, coriander, cayenne, lemon, sherry vinegar), roasted baby beets (balsamic, cumin), tomatillo salsa (garlic, onion, cilantro, lime, green chili), spicy greens",all:"Allium, nightshade, citrus, cilantro, vinegar · gluten cross-contact in meat prep",mods:"Meat can be prepared separately for GF",ut:"Fork / knife",tip:"Printed DF. $3 per piece (steak + tomatillo) at happy hour."},
{cat:"Tapas",name:"Buñuelos de Bacalao",price:"12",hh:"3",ill:"plate",drop:"Crispy salt-cod fritters with garlic and parsley, with piquillo cream sauce for dipping.",ing:"Bacalao, flour, eggs, milk, garlic, parsley, onion, baking powder, piquillo cream (heavy cream, piquillo pepper)",all:"Dairy, allium, nightshade, eggs, fin fish, gluten · fryer cross-contact",mods:"None",ut:"None",tip:"Listed under TAPAS on the 9/11 menu (was aperitivo). $3 per piece at happy hour."},
// ---------- PAELLA ----------
{cat:"Paella",name:"Marinera Fideuà",price:"59",ill:"paella",drop:"Fideuà — toasted fideo noodles in place of rice — with blue crab, shrimp, árbol chili and garlic, finished with saffron sofrito.",ing:"Saffron sofrito, fideo noodles, blue crab, shrimp, garlic, chile de árbol, olive oil, garlic aioli, grilled lemon",all:"Allium, nightshade, shellfish, citrus, gluten (fideo = wheat)",mods:"No garlic aioli; aioli on the side",ut:"Cuchara de paella",tip:"Not gluten-free — fideo is wheat pasta. Printed DF."},
{cat:"Paella",name:"Rabo de Toro",price:"55",ill:"paella",drop:"Paella with braised oxtail, piparra pepper and red wine.",ing:"Saffron sofrito, bomba rice, braised oxtail (red wine), piparra pepper, olive oil",all:"Allium, nightshade, alcohol",mods:"Piparra on the side",ut:"Cuchara de paella",tip:"Printed GF · DF."},
{cat:"Paella",name:"Americana",price:"50",ill:"paella",drop:"Our house paella — boneless chicken thigh, Catalan sausage and chorizo with cauliflower, romano beans and broccolini over saffron rice.",ing:"Saffron sofrito, bomba rice, boneless chicken thigh, Catalan sausage (botifarra), chorizo, cauliflower, romano bean, broccolini, olive oil",all:"Allium, nightshade, pork",mods:"None",ut:"Cuchara de paella",tip:"NEW on the 9/11 menu · printed GF · DF · the cheapest paella at $50."},
{cat:"Paella",name:"Señorito",price:"56",ill:"paella",drop:"Seafood paella with whitefish, calamari and prawns — 'señorito' because it's all peeled and ready to eat, nothing to wrestle with.",ing:"Saffron sofrito (onion, celery, tomato, piquillo, garlic), bomba rice, whitefish, calamari, prawns, garlic, parsley, garlic aioli",all:"Fish, shellfish, mollusk, allium, nightshade, citrus",mods:"No garlic aioli; aioli on the side",ut:"Cuchara de paella",tip:"Printed GF · DF. Menu says whitefish — don't promise mahi."},
{cat:"Paella",name:"Valenciana",price:"54",ill:"paella",drop:"The original — paella with chicken, romano and white beans, artichoke, rosemary and saffron.",ing:"Saffron sofrito, chicken, bomba rice, romano bean, white bean, rosemary, artichoke, parsley, olive oil",all:"Allium, nightshade, citrus",mods:"None",ut:"Cuchara de paella",tip:"Printed GF · DF."},
{cat:"Paella",name:"Primavera",price:"42",ill:"paella",drop:"Vegetable paella — green beans, asparagus, spinach pesto, piquillo, mushrooms, artichoke and zucchini over saffron rice.",ing:"Bomba rice, vegetable stock, green beans, asparagus, spinach pesto, piquillo, mushrooms, artichoke, zucchini, sofrito, saffron",all:"Allium, nightshade, legumes",mods:"None",ut:"Cuchara de paella",tip:"The vegan paella — printed GF · VG · DF. Confirm the pesto has no cheese or nuts before promising it."},
// ---------- POSTRES (Sweet Tapas menu 6.24.26) ----------
{cat:"Postres",name:"AvenChurros",price:"14",ill:"dessert",drop:"Classic churros dusted with cinnamon sugar, with caramel and chocolate sauce for dipping.",ing:"Churro batter (sugar, butter, flour, milk, eggs), chocolate sauce (cream, coffee, corn syrup, dark chocolate, cocoa), caramel (EVOO, sugar, cream, butter, corn syrup, vanilla paste)",all:"Dairy, eggs, corn, caffeine, gluten",mods:"None",ut:"None (finger food)",pair:"Lustau 'San Emilio' Pedro Ximénez Sherry",tip:"Printed V. Top dessert seller — offer the PX or a Carajillo. Happy hour has mini 'Churritos y Chocolate' for $6."},
{cat:"Postres",name:"Tarta de Queso",price:"15",ill:"dessert",drop:"Traditional Basque burnt cheesecake.",ing:"Cream cheese, mascarpone, sugar, eggs, yolks, vanilla, salt, flour",all:"Dairy, eggs, gluten",mods:"None",ut:"Fork",pair:"Lustau 'East India' Cream Sherry",tip:"Printed V."},
{cat:"Postres",name:"Goxua",price:"15",ill:"dessert",drop:"A Basque-inspired trifle of passion fruit curd, chiffon cake and mascarpone.",ing:"Passion fruit curd (purée, sugar, eggs, PORCINE gelatin, butter), lemon chiffon cake (egg, oil, lemon zest, GF flour), mascarpone mousse (mascarpone, cream, powdered sugar, vanilla)",all:"Pork (gelatin), alcohol, dairy, eggs",mods:"None",ut:"Spoon",pair:"César Florido 'Moscatel Dorado' Sherry",tip:"Printed GF. Contains porcine gelatin — not vegetarian, not halal/kosher."},
{cat:"Postres",name:"Torrijas",price:"15",ill:"dessert",drop:"Spanish 'French toast' — rum-soaked brioche, brûléed, with strawberry, vanilla mascarpone and mint.",ing:"Brioche (flour, yeast, milk, eggs, butter), soak (egg yolk, cream, milk, brown sugar, vanilla paste, Sailor Jerry dark rum — nutmeg, cinnamon, clove), strawberries, vanilla mascarpone, mint",all:"Dairy, eggs, gluten, alcohol",mods:"None",ut:"Fork",pair:"Lustau 'East India Solera' Cream Sherry",tip:"Printed V."},
{cat:"Postres",name:"Tarta de Santiago",price:"12",ill:"dessert",drop:"Traditional Galician almond cake with powdered sugar, served with vanilla ice cream.",ing:"Almond flour, sugar, eggs, powdered sugar, vanilla ice cream",all:"Tree nuts, eggs, dairy (ice cream)",mods:"No ice cream",ut:"Fork / knife",pair:"Rare Wine Co 'Boston Bual' Madeira",tip:"Printed GF — the go-to dessert for gluten-free guests. Comes with ice cream, so not dairy-free as printed."},
{cat:"Postres",name:"Bizcocho de Chocolate y Pistacho",price:"13",ill:"dessert",drop:"Milk chocolate and olive-oil brownie with pistachio and sea salt.",ing:"Milk chocolate, butter, olive oil, brown sugar, eggs, flour, cocoa, vanilla, pistachio, sea salt",all:"Tree nuts (pistachio), eggs, gluten, dairy",mods:"None",ut:"Dessert spoon",pair:"Cardamaro Vino Aperitivo",tip:"Menu prints no diet flags — vegetarian in practice, but confirm with Chef."},
// ---------- HAPPY HOUR ONLY (8.1.26) ----------
{cat:"Happy Hour",name:"Gildas Tradicional",price:"2 / piece",hh:"2",ill:"plate",drop:"The classic pintxo — boquerón, piparra pepper, cornichon and a Spanish olive on a skewer.",ing:"Boquerón (white anchovy), piparra/guindilla pepper, cornichon, Spanish olive",all:"Fin fish, nightshade, vinegar, sunflower",mods:"None",ut:"None",tip:"$2 bite · happy hour only (3–6pm daily & 9pm–close). One bite = the original Basque pintxo."},
{cat:"Happy Hour",name:"Jamón y Manchego",price:"3 / piece",hh:"3",ill:"plate",drop:"Jamón serrano and manchego with quince on a crostini.",ing:"Jamón serrano, manchego, quince (membrillo), crostini",all:"Pork, dairy, gluten",mods:"None",ut:"None",tip:"$3 bite · happy hour only."},
{cat:"Happy Hour",name:"Papas Fritas y Jamón",price:"10",hh:"10",ill:"bowl",drop:"House-seasoned potato chips with Fermín jamón serrano.",ing:"House chips (russet, pimentón dulce & picante, espelette, tomato powder, garlic & onion powder, MSG), Fermín jamón serrano",all:"Pork, nightshade, allium · fryer cross-contact",mods:"None",ut:"None",tip:"Happy hour 'para compartir' only."},
{cat:"Happy Hour",name:"Churritos y Chocolate",price:"6",hh:"6",ill:"dessert",drop:"Mini churros with chocolate sauce.",ing:"Churro batter (sugar, butter, flour, milk, eggs), chocolate sauce (cream, coffee, corn syrup, dark chocolate, cocoa)",all:"Dairy, eggs, corn, caffeine, gluten",mods:"None",ut:"None (finger food)",tip:"Happy hour only — the dinner version is AvenChurros ($14, with caramel too)."},
];
// Happy hour prices for dinner items are on the `hh` field. Printed diet codes: V vegetarian · VG vegan · GF · DF (see diet.js)
