// Resource guide facts + wines by the glass. Menus: Dinner 9.11.26 · Sweet Tapas 6.24.26 · Happy Hour 8.1.26
const FACTS=[
// House Pours
{cat:"House Pours",q:"House vodka?",a:"Tito's",x:"Austin, Texas — distilled from corn"},
{cat:"House Pours",q:"House gin?",a:"Citadelle",x:"Maison Ferrand, Cognac, France — 19 botanicals"},
{cat:"House Pours",q:"House rum?",a:"Flor de Caña",x:"Blended white rum from Nicaragua"},
{cat:"House Pours",q:"House tequila?",a:"Exotico Blanco",x:"Unaged Blue Weber agave, Mexico"},
{cat:"House Pours",q:"House mezcal?",a:"Banhez",x:"San Miguel Ejutla — smoky, unaged Espadín"},
{cat:"House Pours",q:"House bourbon?",a:"Maker's Mark",x:"Kentucky — corn, wheat & malted barley"},
{cat:"House Pours",q:"House rye?",a:"Rittenhouse",x:"Pennsylvania"},
{cat:"House Pours",q:"Standard pour size?",a:"1.5 oz",x:"Single = one standard shot · dessert wines & sherries pour 2.5 oz"},
// Service & Glassware
{cat:"Service & Glassware",q:"A guest orders it \"up\" — that means?",a:"Chilled, no ice, in a stemmed glass",x:"Same as \"straight up\""},
{cat:"Service & Glassware",q:"\"Neat\" means?",a:"No ice, no chill — straight into the glass",x:""},
{cat:"Service & Glassware",q:"\"Dirty\" means?",a:"Addition of olive brine",x:""},
{cat:"Service & Glassware",q:"A \"perfect\" Manhattan uses?",a:"Equal parts dry & sweet vermouth",x:""},
{cat:"Service & Glassware",q:"\"Double\" means?",a:"Two shots of spirit in one drink",x:""},
{cat:"Service & Glassware",q:"\"Tall\" vs \"short\"?",a:"Tall = taller glass, more mixer · short = smaller glass, stronger",x:""},
{cat:"Service & Glassware",q:"The coupe is used for?",a:"Most up crafted cocktails",x:"La Huerta, Sueños de Suerte"},
{cat:"Service & Glassware",q:"The rocks glass is used for?",a:"Cocktails on the rocks or over a king cube",x:"Pasión Ciega & Carajillo"},
{cat:"Service & Glassware",q:"The neat glass is used for?",a:"Shots",x:""},
{cat:"Service & Glassware",q:"The champagne flute is used for?",a:"Sparkling wine by the glass & bottle",x:"Both cavas"},
{cat:"Service & Glassware",q:"The Nick & Nora is used for?",a:"Spirit-forward cocktails",x:"Mare Nostrum"},
{cat:"Service & Glassware",q:"The tulip glass is used for?",a:"N/A beers",x:"Plus tulip NA builds like El Parque & Dama Rosa"},
{cat:"Service & Glassware",q:"The goblet is used for?",a:"Gin tonics & sangria by the glass",x:""},
{cat:"Service & Glassware",q:"The Collins glass holds?",a:"Still Sant Aniol water, beer, cider, highballs & long cocktails",x:"El Arbol, El Intercambio, La Abeja Sonriente"},
{cat:"Service & Glassware",q:"The wine glass (bar side) is for?",a:"Sparkling Sant Aniol water & spritzes",x:""},
{cat:"Service & Glassware",q:"The white wine glass is used for?",a:"Sangria pitcher service",x:""},
{cat:"Service & Glassware",q:"The 'AP' glass is used for?",a:"All by-the-glass still wine",x:"AP = all purpose"},
// Menu Basics (printed on the menus)
{cat:"Menu Basics",q:"How long does a paella take?",a:"Up to 45 minutes — each is made to order",x:"Set the expectation at the order, not when the guest asks"},
{cat:"Menu Basics",q:"How many people does a paella feed?",a:"2–3 servings",x:"Printed on the menu — 'National dish of Spain'"},
{cat:"Menu Basics",q:"Sunday paella deal?",a:"25% off every paella, every Sunday",x:"Printed on the dinner menu — 'Like a Spaniard'"},
{cat:"Menu Basics",q:"The surcharge on every bill?",a:"3% — printed on the menu to offset rising operational costs",x:"Guests can read more at thepulpogroup.com/surcharge"},
{cat:"Menu Basics",q:"Menu diet codes?",a:"GF gluten-free · V vegetarian · VG vegan · DF dairy-free",x:"V = vegetarian and VG = vegan on our printed menu — don't mix them up"},
{cat:"Menu Basics",q:"How big is a dessert-wine pour?",a:"2.5 oz — every glass on the Vino de Postre list",x:"Sherries, Madeiras and the Moscatel"},
{cat:"Menu Basics",q:"Three menus in service right now?",a:"Dinner (9.11.26), Sweet Tapas (6.24.26) & Happy Hour (8.1.26)",x:"Sweet Tapas = postres, vino de postre & café"},
// Happy Hour
{cat:"Happy Hour",q:"Happy hour hours?",a:"3–6pm daily & every night 9pm–close",x:""},
{cat:"Happy Hour",q:"Happy hour drink deal?",a:"25% off ALL drinks",x:"Cocktails, wine, beer, cider, NA — everything"},
{cat:"Happy Hour",q:"The $2 bites (Bocados)?",a:"Gildas Tradicional · Croqueta de Manchego · Croqueta de Setas · Croqueta de Jamón",x:"Priced per piece — guests write a quantity on the card"},
{cat:"Happy Hour",q:"The $3 bites (Clásicos)?",a:"Dátiles con Chorizo · Buñuelos de Bacalao · Jamón y Manchego · Almendras y Piña · Pintxos Morunos",x:"Priced per piece"},
{cat:"Happy Hour",q:"Happy hour 'Para Compartir' plates?",a:"Papas Fritas y Jamón 10 · Pan a la Catalana 8 · Patatas Bravas 8 · Pimientos de Padrón 7 · Churritos y Chocolate 6",x:"Pan a la Catalana: +2 jamón, +2 boquerones · Bravas: +2 jamón, +2 fried egg"},
{cat:"Happy Hour",q:"Happy hour price vs dinner price — Patatas Bravas?",a:"$8 at happy hour · $10 at dinner",x:"Padrón is $7 vs $11 · Pan a la Catalana $8 vs $11"},
{cat:"Happy Hour",q:"What is 'Jamón y Manchego'?",a:"Jamón serrano, manchego, quince on a crostini — $3 happy hour bite",x:"Happy hour only"},
{cat:"Happy Hour",q:"What are 'Churritos y Chocolate'?",a:"Mini churros with chocolate sauce — $6 happy hour plate",x:"Dinner churros (AvenChurros) are $14 with caramel & chocolate"},
{cat:"Happy Hour",q:"Papas Fritas y Jamón?",a:"House-seasoned potato chips with Fermín jamón serrano — $10",x:"Happy hour only · shared fryer"},
// Spirits 101
{cat:"Spirits 101",q:"The defining botanical of gin?",a:"Juniper",x:""},
{cat:"Spirits 101",q:"Tequila must be made from?",a:"Blue Weber agave from specific regions of Mexico",x:"Mezcal can use many agave types — often smokier"},
{cat:"Spirits 101",q:"Blanco means?",a:"Unaged (clear)",x:""},
{cat:"Spirits 101",q:"Reposado means?",a:"Aged 2+ months in barrel (pale gold)",x:""},
{cat:"Spirits 101",q:"Añejo means?",a:"Aged 1+ year in barrel (deep gold)",x:""},
{cat:"Spirits 101",q:"Bourbon rules?",a:"USA, 51%+ corn, aged in new charred oak",x:""},
{cat:"Spirits 101",q:"Rye whiskey rules?",a:"USA, 51%+ rye — spicier",x:""},
{cat:"Spirits 101",q:"Scotch rules?",a:"Made in Scotland, aged 3+ years, often barley-based",x:""},
{cat:"Spirits 101",q:"Brandy is distilled from?",a:"Wine (grapes)",x:"Cognac: double-distilled, 2+ yrs"},
{cat:"Spirits 101",q:"Orujo is?",a:"A pomace brandy from northern Spain",x:""},
{cat:"Spirits 101",q:"Licor de Hierbas is?",a:"Spanish herbal liqueur",x:"Anise, mint, chamomile, rosemary, thyme, citrus peels"},
{cat:"Spirits 101",q:"Amaro is?",a:"Italian bittersweet herbal liqueur — 'amaro' means bitter",x:"Gentian, wormwood, cinchona, citrus, cardamom"},
{cat:"Spirits 101",q:"Rum & cachaça are distilled from?",a:"Sugarcane — juice or molasses",x:""},
// Wine 101
{cat:"Wine 101",q:"Terroir means?",a:"The complete natural environment — soil, climate, topography, local yeasts",x:""},
{cat:"Wine 101",q:"Vintage means?",a:"The year the grapes were harvested",x:""},
{cat:"Wine 101",q:"US varietal labeling rule?",a:"The wine must contain at least 75% of that grape",x:""},
{cat:"Wine 101",q:"Appellation means?",a:"A legally defined, protected place of origin",x:"e.g. Rioja, Napa Valley, Chablis"},
{cat:"Wine 101",q:"Tannin is?",a:"A drying, puckering compound from grape skins, seeds & stems",x:"Like strong tea — adds structure & aging potential"},
{cat:"Wine 101",q:"Acidity in wine feels like?",a:"Tartness/freshness — zippy & mouthwatering",x:"Essential for balance & food pairing"},
{cat:"Wine 101",q:"Body means?",a:"The weight of the wine in your mouth",x:"Skim milk (light) vs whole milk (full)"},
{cat:"Wine 101",q:"Minerality describes?",a:"Crushed rock, chalk, flint or saline qualities",x:"Often associated with terroir"},
{cat:"Wine 101",q:"Finish means?",a:"The lingering taste after you swallow",x:"Long & pleasant = quality"},
{cat:"Wine 101",q:"Old World style?",a:"Europe — more acid, more earth/mineral, less oak",x:""},
{cat:"Wine 101",q:"New World style?",a:"USA, S. America, Australia, S. Africa — less acid, more fruit & oak",x:""},
{cat:"Wine 101",q:"Spicy food pairs with?",a:"Sweetness in wine — it offsets spice",x:""},
{cat:"Wine 101",q:"Tannic reds are best balanced with?",a:"Fat",x:""},
{cat:"Wine 101",q:"Match the wine with the ____, not the meat.",a:"Sauce",x:""},
{cat:"Wine 101",q:"Txakolina (chacolí) is?",a:"A light, high-acid Basque wine — usually a little spritzy",x:"Our red one: Ameztoi 'Stimatum' from Getaria"},
{cat:"Wine 101",q:"Cava is made how?",a:"Traditional method — second fermentation in the bottle, like Champagne",x:"'Brut Nature' = no added sugar"},
// Sherry & Vermouth
{cat:"Sherry & Vermouth",q:"Fino / Manzanilla?",a:"Lightest sherries — aged under flor; salty & razor-crisp, serve cold",x:"Olives, Marcona almonds, oysters"},
{cat:"Sherry & Vermouth",q:"Amontillado?",a:"An aged Fino — flor fades, wine oxidizes; salty bite + nutty richness",x:""},
{cat:"Sherry & Vermouth",q:"Palo Cortado?",a:"Rare style — flor dies unexpectedly; rich yet delicate",x:""},
{cat:"Sherry & Vermouth",q:"Oloroso?",a:"Never develops flor — fully oxidative; full-bodied, dark, spicy",x:"Drink like a fine bourbon"},
{cat:"Sherry & Vermouth",q:"Pedro Ximénez (PX)?",a:"The sweetest sherry — sun-dried grapes; raisin, fig, chocolate",x:"Lustau San Emilio — pairs with the AvenChurros"},
{cat:"Sherry & Vermouth",q:"Cream sherry?",a:"Oloroso sweetened with PX — dried fruit, cocoa, walnut",x:"Lustau 'East India Solera' — pairs with Tarta de Queso & Torrijas"},
{cat:"Sherry & Vermouth",q:"The Sherry Triangle?",a:"Jerez de la Frontera, Sanlúcar de Barrameda, El Puerto de Santa María",x:""},
{cat:"Sherry & Vermouth",q:"Vermouth must be at least?",a:"75% wine, plus sugar/mistelle, botanicals & alcohol",x:"Every vermouth contains an artemisia (bitter root)"},
{cat:"Sherry & Vermouth",q:"Sherry ABV range?",a:"15% to over 20%",x:"Pour smaller — 2.5 oz on the dessert list"},
{cat:"Sherry & Vermouth",q:"Madeira is?",a:"Fortified wine from the island of Madeira, heated & oxidized on purpose — nearly indestructible once open",x:"Rare Wine Co 'Boston Bual' (medium-sweet) & 'New York Malmsey' (sweet)"},
{cat:"Sherry & Vermouth",q:"Cardamaro is?",a:"An Italian wine-based aperitivo with cardoon & blessed thistle — gentle, nutty, honeyed",x:"Pairs with the Bizcocho de Chocolate y Pistacho"},
// Beer & Cider
{cat:"Beer & Cider",q:"Our exclusive house beer?",a:"Mothfire 'Octo' lightly hopped ale — $10",x:"Ann Arbor · brewed exclusively for The Pulpo Group — poured at all 3 restaurants · crisp, lightly citrusy, not bitter"},
{cat:"Beer & Cider",q:"The hazy IPA?",a:"Mothfire 'Lolo' — $10",x:"Ann Arbor · tropical, juicy, soft bitterness"},
{cat:"Beer & Cider",q:"The Spanish lager?",a:"Estrella Galicia 'Cerveza Especial' — $8",x:"Pale lager · A Coruña, Galicia · crisp & classic"},
{cat:"Beer & Cider",q:"Our NA beers?",a:"Good Time Brewing NA Pils & NA IPA — $8 each",x:"<0.5% abv · New York · serve in the tulip"},
{cat:"Beer & Cider",q:"The cider?",a:"Isastegi Sidra — $8 can · $26 for the 750 mL",x:"Basque sagardo naturala · unfiltered, dry, funky, high-acid · 'a wine lover's cider'"},
{cat:"Beer & Cider",q:"The non-alcoholic cider?",a:"Trabanco Sidra Natural Sin Alcohol — $26 (700 mL bottle)",x:"Asturias, Spain — bottle only, great for a table that isn't drinking"},
// NA Program
{cat:"NA Program",q:"Our water?",a:"Sant Aniol — natural mineral water of volcanic origin",x:"Filtered through volcanic rock in La Garrotxa, Catalonia"},
{cat:"NA Program",q:"Our soda?",a:"Motor City Soda — Leonard's Syrups, Detroit",x:"Cola, Diet, Twin-Up, Golden Ginger Ale, Lemonade, Quinine Tonic"},
{cat:"NA Program",q:"Our tea?",a:"Arbor Teas — organic, from Ann Arbor · $7",x:"Dandelion root, crimson berry, vanilla almond rooibos, chamomile, Moroccan mint, decaf earl grey, butterfly pea lemongrass, masala chai"},
{cat:"NA Program",q:"Our coffee?",a:"RoosRoast — Ann Arbor · Lobster Butter Love drip $4",x:"Americano $6 · Espresso $4 single / $7 double (Roos machine espresso)"},
{cat:"NA Program",q:"Butterfly pea flower party trick?",a:"Changes from blue to purple with a squeeze of citrus (pH)",x:""},
{cat:"NA Program",q:"NA options that aren't mocktails?",a:"Good Time NA Pils & IPA, Trabanco NA cider, Arbor Teas, RoosRoast coffee, Sant Aniol",x:"Plus El Parque, Sueños de Suerte & Dama Rosa"},
];
// Wines by the glass — Dinner menu 9.11.26. kind: sparkling | rose | white | red | dessert
const WINES=[
{cat:"Wines BTG",kind:"sparkling",name:"Cava Torremilanos Peñalba López, Brut Nature",region:"Ribera del Duero",price:"18 / 72",notes:"bright citrus, creamy texture, apple, brioche",grape:"Traditional-method cava — confirm the blend with the rep",story:"One of the rare cavas made outside Catalonia — the Peñalba López family's organic estate in Aranda de Duero · Brut Nature = zero dosage",like:"Champagne",pair:"Pan a la Catalana, encurtidos, croquetas, buñuelos"},
{cat:"Wines BTG",kind:"rose",name:"Rosé Cava Portell, Brut",region:"Penedès",price:"14 / 56",notes:"rhubarb, wild strawberry, blood orange",grape:"Trepat (the Catalan rosé-cava grape) — confirm",story:"Cooperative-grown, traditional method; pale pink with fine bubbles",like:"Rosé Champagne / crémant rosé",pair:"Quesos y charcutería, dátiles, gambas"},
{cat:"Wines BTG",kind:"white",name:"Macabeo Tardano",region:"Penedès 2024",price:"15 / 60",notes:"orchard fruit, citrus, fennel",grape:"100% Macabeo (Viura's Catalan name)",story:"The cava grape, made still — dry, fresh, unoaked · ask the rep for the producer story",like:"Pinot Grigio / Vermentino",pair:"Encurtidos, tortilla, crudo de atún"},
{cat:"Wines BTG",kind:"white",name:"Albarín Blanco Pardevalles",region:"Castilla y León 2024",price:"14 / 56",notes:"elderflower, lemongrass, brown pear",grape:"100% Albarín Blanco (NOT Albariño!)",story:"Pardevalles grows around 20% of the world's Albarín Blanco — a rare native grape of León",like:"Chenin Blanc / Viognier blend",pair:"Almendras y piña, patatas bravas, setas"},
{cat:"Wines BTG",kind:"white",name:"Albariño Jorge Ordóñez 'La Caña'",region:"Rías Baixas 2025",price:"15 / 60",notes:"peach, apricot, meyer lemon, white flower",grape:"100% Albariño",story:"Old-vine fruit from the Salnés Valley, aged on the lees — from the Jorge Ordóñez portfolio",like:"Muscadet / Grüner Veltliner",pair:"Pulpo, gambas, Señorito paella, sardinas"},
{cat:"Wines BTG",kind:"white",name:"Malvasía Blend Bodegas Almaroja 'Pirita Blanco'",region:"Castilla y León 2023",price:"17 / 68",notes:"floral aromatic, complex minerality, pear, apricot, honeyed texture",grape:"Malvasía-led field blend with old local varieties",story:"Charlotte Allen's biodynamic estate in Arribes del Duero, on the Portuguese border · 'pirita' = pyrite, the fool's gold in the granite soils",like:"Textured, aromatic white — think dry Chenin or Grüner",pair:"Flor de alcachofa, pluma katsu, Valenciana paella"},
{cat:"Wines BTG",kind:"white",name:"Viura Blend Ostatu",region:"Rioja Alavesa 2024",price:"13 / 52",notes:"quince, lemon zest, limestone",grape:"85% Viura, 15% Malvasía",story:"Family growing grapes for 250+ years · native yeast, stainless steel",like:"Pinot Grigio",pair:"Encurtidos, gambas, Señorito paella"},
{cat:"Wines BTG",kind:"rose",name:"Sumoll / Xarel·lo Can Sumoi 'La Rosa'",region:"Penedès 2024",price:"17 / 68",notes:"strawberry, basil, kiwi, red currant",grape:"Sumoll, Xarel·lo & Parellada",story:"Pepe Raventós's natural-wine project at 600 m in the Penedès mountains — organic, wild yeast, minimal sulfur",like:"Provence rosé with more texture",pair:"Pan a la Catalana, gambas, Primavera paella, crudo"},
{cat:"Wines BTG",kind:"red",name:"Hondarrabi Beltza Ameztoi 'Stimatum'",region:"Getariako Txakolina 2024",price:"15 / 60",notes:"wild berries, tart cherry, lively acidity, natural spritz",grape:"100% Hondarrabi Beltza",story:"A RED txakoli from Getaria on the Basque coast — light, chillable, a touch of spritz; serve cool",like:"Chilled Gamay / Beaujolais",pair:"Anchoas, sardinas, pintxos morunos, dátiles"},
{cat:"Wines BTG",kind:"red",name:"Mencía Merayo 'Las Tres Filas'",region:"Bierzo 2023",price:"14 / 56",notes:"fresh red berries, silky tannins, subtle minerality",grape:"100% Mencía",story:"Young, unoaked Mencía from old vines in Bierzo (northwest Spain) — 'three rows' of the family's vineyard",like:"Unoaked Pinot Noir / Cru Beaujolais",pair:"Pulpo a la gallega, setas, tortilla"},
{cat:"Wines BTG",kind:"red",name:"Callet Blend Mesquida Mora 'Sincronía Negre'",region:"Mallorca 2024",price:"15 / 60",notes:"fresh red berries, silky tannins, subtle minerality",grape:"Callet & Manto Negro (Mallorcan natives) with a little Syrah & Cabernet — confirm",story:"Bàrbara Mesquida Mora farms biodynamically in the middle of Mallorca — the island's native grapes, made fresh",like:"Juicy Grenache / Cinsault",pair:"Dátiles con chorizo, Americana paella, berenjena frita"},
{cat:"Wines BTG",kind:"red",name:"Cariñena Alemany i Corrió 'El Microscopi'",region:"Barcelona 2025",price:"19 / 76",notes:"juicy dark berries, mediterranean herbs & spice, elegant tannin",grape:"100% Cariñena (Carignan)",story:"Irene Alemany & Laurent Corrió, tiny biodynamic cellar in Penedès — the 'microscope' is a close-up look at one old-vine grape",like:"Old-vine Carignan / Priorat, fresher",pair:"Pintxos morunos, Rabo de Toro paella, pluma katsu"},
{cat:"Wines BTG",kind:"red",name:"Tempranillo Volver Tinto",region:"La Mancha 2022",price:"17 / 68",notes:"black currant, plum, subtle toast, mellow tannin",grape:"100% Tempranillo",story:"Single 1957 vineyard on sandy iron-rich soil · 14 months in used French oak · NOT Rioja — La Mancha",like:"Mellow Rioja Crianza",pair:"Bold meats — pintxos morunos, Rabo de Toro"},
{cat:"Wines BTG",kind:"red",name:"Monastrell Bodegas Carchelo 'C'",region:"Jumilla 2019",price:"13 / 50",notes:"blackberry bramble, blueberry, violet",grape:"Monastrell (Mourvèdre) — Jumilla's signature grape",story:"Old bush vines on limestone in Jumilla, southeast Spain — the ripe, easy-drinking house red",like:"Southern Rhône / Zinfandel",pair:"Dátiles con chorizo, croquetas de jamón, Americana paella"},
// Vino de Postre — Sweet Tapas menu · all pours 2.5 oz
{cat:"Vino de Postre",kind:"dessert",name:"César Florido 'Moscatel Dorado'",region:"Chipiona · Sherry region",price:"11 (2.5 oz)",notes:"orange blossom, honey, jasmine tea, vanilla bean",grape:"Moscatel de Alejandría",story:"Chipiona, the Moscatel capital of the sherry triangle — lightly fortified, golden, gently sweet",like:"Muscat de Beaumes-de-Venise",pair:"Goxua (its printed pairing), tarta de Santiago"},
{cat:"Vino de Postre",kind:"dessert",name:"Lustau 'East India Solera' Cream Sherry",region:"Jerez",price:"10 (2.5 oz)",notes:"dried fruits, cocoa, orange peel, walnuts, earl grey tea",grape:"Palomino (Oloroso) + Pedro Ximénez",story:"Oloroso sweetened with PX, then aged in a warm solera to echo the old 'East India' ships that shipped sherry across the equator",like:"Tawny port",pair:"Tarta de Queso & Torrijas (printed pairings)"},
{cat:"Vino de Postre",kind:"dessert",name:"Lustau 'San Emilio' Pedro Ximénez",region:"Jerez",price:"10 (2.5 oz)",notes:"sweet, chocolate, raisin, dried fig",grape:"100% Pedro Ximénez, sun-dried",story:"The sweetest sherry — grapes dried on straw mats before pressing; pour it over ice cream if a guest asks",like:"Liquid raisins — richer than any port",pair:"AvenChurros (printed pairing), bizcocho"},
{cat:"Vino de Postre",kind:"dessert",name:"Rare Wine Co 'Boston Bual' Madeira",region:"Madeira, Portugal",price:"16 (2.5 oz)",notes:"medium sweet, date, black walnut, toffee",grape:"Bual",story:"Historic Series — made by Barbeito in the style colonial-era Boston drank; heated & oxidized on purpose, so an open bottle lasts for months",like:"Nutty, tangy tawny — with acidity",pair:"Tarta de Santiago (printed pairing), quesos"},
{cat:"Vino de Postre",kind:"dessert",name:"Rare Wine Co 'New York Malmsey' Madeira",region:"Madeira, Portugal",price:"16 (2.5 oz)",notes:"sweet, candied nuts, dark caramel, baking spice",grape:"Malvasia (Malmsey — the sweetest style)",story:"Historic Series — the richest of the four classic Madeira styles; New York's favorite in the 1700s",like:"PX sherry with more acid and spice",pair:"AvenChurros, bizcocho, tarta de queso"},
];
