const FACTS=[
// House Pours
{cat:"House Pours",q:"House vodka?",a:"Tito's",x:"Austin, Texas — distilled from corn"},
{cat:"House Pours",q:"House gin?",a:"Citadelle",x:"Maison Ferrand, Cognac, France — 19 botanicals"},
{cat:"House Pours",q:"House rum?",a:"Flor de Caña",x:"Blended white rum from Nicaragua"},
{cat:"House Pours",q:"House tequila?",a:"Exotico Blanco",x:"Unaged Blue Weber agave, Mexico"},
{cat:"House Pours",q:"House mezcal?",a:"Banhez",x:"San Miguel Ejutla — smoky, unaged Espadín"},
{cat:"House Pours",q:"House bourbon?",a:"Maker's Mark",x:"Kentucky — corn, wheat & malted barley"},
{cat:"House Pours",q:"House rye?",a:"Rittenhouse",x:"Pennsylvania"},
{cat:"House Pours",q:"Standard pour size?",a:"1.5 oz",x:"Single = one standard shot"},
// Service & Glassware
{cat:"Service & Glassware",q:"A guest orders it \"up\" — that means?",a:"Chilled, no ice, in a stemmed glass",x:"Same as \"straight up\""},
{cat:"Service & Glassware",q:"\"Neat\" means?",a:"No ice, no chill — straight into the glass",x:""},
{cat:"Service & Glassware",q:"\"Dirty\" means?",a:"Addition of olive brine",x:""},
{cat:"Service & Glassware",q:"A \"perfect\" Manhattan uses?",a:"Equal parts dry & sweet vermouth",x:""},
{cat:"Service & Glassware",q:"\"Double\" means?",a:"Two shots of spirit in one drink",x:""},
{cat:"Service & Glassware",q:"\"Tall\" vs \"short\"?",a:"Tall = taller glass, more mixer · short = smaller glass, stronger",x:""},
{cat:"Service & Glassware",q:"The coupe is used for?",a:"Most up crafted cocktails",x:""},
{cat:"Service & Glassware",q:"The rocks glass is used for?",a:"Cocktails on the rocks or over a king cube",x:"Pasión Ciega & Carajillo"},
{cat:"Service & Glassware",q:"The neat glass is used for?",a:"Shots",x:""},
{cat:"Service & Glassware",q:"The champagne flute is used for?",a:"Sparkling wine by the glass & bottle",x:""},
{cat:"Service & Glassware",q:"The Nick & Nora is used for?",a:"Spirit-forward cocktails",x:""},
{cat:"Service & Glassware",q:"The tulip glass is used for?",a:"N/A beers",x:"Plus tulip NA builds like El Parque & Dama Rosa"},
{cat:"Service & Glassware",q:"The goblet is used for?",a:"Gin tonics & sangria by the glass",x:""},
{cat:"Service & Glassware",q:"The Collins glass holds?",a:"Still Sant Aniol water, beer, cider, highballs & long cocktails",x:""},
{cat:"Service & Glassware",q:"The wine glass (bar side) is for?",a:"Sparkling Sant Aniol water & spritzes",x:""},
{cat:"Service & Glassware",q:"The white wine glass is used for?",a:"Sangria pitcher service",x:""},
{cat:"Service & Glassware",q:"The 'AP' glass is used for?",a:"All by-the-glass still wine",x:"AP = all purpose"},
// Spirits 101
{cat:"Spirits 101",q:"The defining botanical of gin?",a:"Juniper",x:""},
{cat:"Spirits 101",q:"Tequila must be made from?",a:"Blue Weber agave from specific regions of Mexico",x:"Mezcal can use many agave types — often smokier"},
{cat:"Spirits 101",q:"Blanco means?",a:"Unaged (clear)",x:""},
{cat:"Spirits 101",q:"Reposado means?",a:"Aged 2+ months in barrel (pale gold)",x:""},
{cat:"Spirits 101",q:"Añejo means?",a:"Aged 1+ year in barrel (deep gold)",x:""},
{cat:"Spirits 101",q:"Bourbon rules?",a:"USA, 51%+ corn, aged in new charred oak",x:""},
{cat:"Spirits 101",q:"Rye whiskey rules?",a:"USA, 51%+ rye — spicier",x:""},
{cat:"Spirits 101",q:"Scotch rules?",a:"Made in Scotland, aged 3+ years, often barley-based",x:""},
{cat:"Spirits 101",q:"Brandy is distilled from?",a:"Wine (grapes)",x:"Cognac: double-distilled, 2+ yrs"},
{cat:"Spirits 101",q:"Orujo is?",a:"A pomace brandy from northern Spain",x:""},
{cat:"Spirits 101",q:"Licor de Hierbas is?",a:"Spanish herbal liqueur",x:"Anise, mint, chamomile, rosemary, thyme, citrus peels"},
{cat:"Spirits 101",q:"Amaro is?",a:"Italian bittersweet herbal liqueur — 'amaro' means bitter",x:"Gentian, wormwood, cinchona, citrus, cardamom"},
{cat:"Spirits 101",q:"Rum & cachaça are distilled from?",a:"Sugarcane — juice or molasses",x:""},
// Wine 101
{cat:"Wine 101",q:"Terroir means?",a:"The complete natural environment — soil, climate, topography, local yeasts",x:""},
{cat:"Wine 101",q:"Vintage means?",a:"The year the grapes were harvested",x:""},
{cat:"Wine 101",q:"US varietal labeling rule?",a:"The wine must contain at least 75% of that grape",x:""},
{cat:"Wine 101",q:"Appellation means?",a:"A legally defined, protected place of origin",x:"e.g. Rioja, Napa Valley, Chablis"},
{cat:"Wine 101",q:"Tannin is?",a:"A drying, puckering compound from grape skins, seeds & stems",x:"Like strong tea — adds structure & aging potential"},
{cat:"Wine 101",q:"Acidity in wine feels like?",a:"Tartness/freshness — zippy & mouthwatering",x:"Essential for balance & food pairing"},
{cat:"Wine 101",q:"Body means?",a:"The weight of the wine in your mouth",x:"Skim milk (light) vs whole milk (full)"},
{cat:"Wine 101",q:"Minerality describes?",a:"Crushed rock, chalk, flint or saline qualities",x:"Often associated with terroir"},
{cat:"Wine 101",q:"Finish means?",a:"The lingering taste after you swallow",x:"Long & pleasant = quality"},
{cat:"Wine 101",q:"Old World style?",a:"Europe — more acid, more earth/mineral, less oak",x:""},
{cat:"Wine 101",q:"New World style?",a:"USA, S. America, Australia, S. Africa — less acid, more fruit & oak",x:""},
{cat:"Wine 101",q:"Spicy food pairs with?",a:"Sweetness in wine — it offsets spice",x:""},
{cat:"Wine 101",q:"Tannic reds are best balanced with?",a:"Fat",x:""},
{cat:"Wine 101",q:"Match the wine with the ____, not the meat.",a:"Sauce",x:""},
// Sherry & Vermouth
{cat:"Sherry & Vermouth",q:"Fino / Manzanilla?",a:"Lightest sherries — aged under flor; salty & razor-crisp, serve cold",x:"Olives, Marcona almonds, oysters"},
{cat:"Sherry & Vermouth",q:"Amontillado?",a:"An aged Fino — flor fades, wine oxidizes; salty bite + nutty richness",x:""},
{cat:"Sherry & Vermouth",q:"Palo Cortado?",a:"Rare style — flor dies unexpectedly; rich yet delicate",x:""},
{cat:"Sherry & Vermouth",q:"Oloroso?",a:"Never develops flor — fully oxidative; full-bodied, dark, spicy",x:"Drink like a fine bourbon"},
{cat:"Sherry & Vermouth",q:"The Sherry Triangle?",a:"Jerez de la Frontera, Sanlúcar de Barrameda, El Puerto de Santa María",x:""},
{cat:"Sherry & Vermouth",q:"Vermouth must be at least?",a:"75% wine, plus sugar/mistelle, botanicals & alcohol",x:"Every vermouth contains an artemisia (bitter root)"},
{cat:"Sherry & Vermouth",q:"Sherry ABV range?",a:"15% to over 20%",x:"Pour smaller — about half a normal glass"},
// Beer & Cider
{cat:"Beer & Cider",q:"Our exclusive house beer?",a:"Mothfire 'Octo' lightly hopped ale — $10",x:"Ann Arbor · 16oz · 6% · brewed exclusively for The Pulpo Group — poured at all 3 restaurants · crisp, lightly citrusy, not bitter"},
{cat:"Beer & Cider",q:"The hazy IPA?",a:"Mothfire 'Lolo' — $11",x:"16oz · 6.5% · tropical, juicy, soft bitterness"},
{cat:"Beer & Cider",q:"The Spanish lager (bottle list)?",a:"Mahou Cinco Estrellas — $8",x:"12oz · 5.5% · crisp & classic"},
{cat:"Beer & Cider",q:"Our NA beers?",a:"Good Time NA Pils & Good Time NA IPA",x:"Serve in the tulip"},
{cat:"Beer & Cider",q:"The cider?",a:"Isastegi Sidra — $8",x:"Basque sagardo naturala · dry, funky, high-acid · 'a wine lover's cider'"},
// NA Program
{cat:"NA Program",q:"Our water?",a:"Sant Aniol — natural mineral water of volcanic origin",x:"Filtered through volcanic rock in La Garrotxa, Catalonia"},
{cat:"NA Program",q:"Our soda?",a:"Motor City Soda — Leonard's Syrups, Detroit",x:"Cola, Diet, Twin-Up, Golden Ginger Ale, Lemonade, Quinine Tonic"},
{cat:"NA Program",q:"Our tea?",a:"Arbor Teas — organic, from Ann Arbor",x:"Crimson Berry, Butterfly Pea Lemongrass, Chai, Chamomile, Moroccan Mint & more"},
{cat:"NA Program",q:"Our coffee?",a:"RoosRoast — Ann Arbor",x:"Lobster Butter Love, Roos Machine espresso, water-processed decaf"},
{cat:"NA Program",q:"Butterfly pea flower party trick?",a:"Changes from blue to purple with a squeeze of citrus (pH)",x:""},
];
const WINES=[
{name:"Cava Tutusaus 'Brut Nature' Gran Reserva 2021",price:"18 / 72",notes:"white cherry, brioche, almond",grape:"Xarel·lo, Macabeu, Parellada, Chardonnay",story:"Penedès · 36 mo on lees, 0 g/L sugar, biodynamic, 500 cases",like:"Champagne",pair:"Pan a la Catalana, encurtidos, croquetas"},
{name:"Mercat 'Brut Rosé' Cava",price:"13 / 52",notes:"red currant, blood orange, rhubarb",grape:"Macabeu, Xarel·lo, Parellada, Monastrell",story:"Penedès · 18 mo on lees, traditional method",like:"Rosé Champagne",pair:"Quesos y charcutería, croquetas"},
{name:"Olivares Garnacha Rosado, Jumilla 2024",price:"12 / 48",notes:"wild strawberry, orange zest, white pepper",grape:"100% Garnacha",story:"Farmed chemical-free for 80+ years · stainless",like:"Provence rosé",pair:"Pan a la Catalana, gambas, verduras paella"},
{name:"Granbazán 'Etiqueta Verde' Albariño, Rías Baixas 2024",price:"17 / 68",notes:"tangerine, lime, sea spray",grape:"100% Albariño — 35+ yr vines",story:"Granite soils, Salnés Valley · 4 mo on lees, stainless",like:"Muscadet, Grüner Veltliner",pair:"Mussels, pulpo, paella marisco"},
{name:"Ostatu Viura Blend, Rioja Alavesa 2024",price:"13 / 52",notes:"quince, lemon zest, limestone",grape:"85% Viura, 15% Malvasía",story:"Family growing grapes for 250+ years · native yeast, stainless",like:"Pinot Grigio",pair:"Encurtidos, gambas, marisco paella"},
{name:"Pardevalles Albarín Blanco, Tierra de León 2023",price:"14 / 56",notes:"elderflower, lemongrass, brown pear",grape:"100% Albarín Blanco (not Albariño!)",story:"Grows 20% of the world's Albarín Blanco",like:"Chenin Blanc / Viognier blend",pair:"Almendras y piña, patatas bravas"},
{name:"Alemany i Corrió 'Principia Mathematica' Xarel·lo 2022",price:"18 / 72",notes:"apricot, baking spice, buttered almond",grape:"100% Xarel·lo",story:"Oak + stainless (tart & creamy) · biodynamic, 600 cases",like:"White Burgundy",pair:"Croquetas, paella marisco"},
{name:"Marimar Estate 'La Masía' Chardonnay, Russian River 2023",price:"24 / 96",notes:"golden apple, vanilla, baking spice",grape:"100% Chardonnay",story:"Winemaker Marimar Torres · French oak 33% new, full malo",like:"Classic California Chardonnay",pair:"Tortilla española, Valenciana paella"},
{name:"'El Reflejo de Mikaela' Bobal, Ribera del Júcar 2020",price:"19 / 76",notes:"red & black berries, plum, silky",grape:"90% Bobal",story:"50-yr vines, organic, fields plowed by horse",like:"Pinot Noir",pair:"Tortilla, dátiles con chorizo"},
{name:"Fento 'Ollo de Sapo' Mencía, Ribeira Sacra",price:"14 / 56",notes:"blackberry, thyme, pepper",grape:"100% Mencía",story:"'Eye of the frog' granite soils · all stainless, fresh & mineral",like:"Unoaked Pinot Noir / S. Rhône",pair:"Pulpo a la gallega, setas"},
{name:"Volver Single Vineyard Tempranillo, La Mancha 2022",price:"17 / 68",notes:"black currant, plum, mellow tannin",grape:"100% Tempranillo",story:"1957 vineyard, sandy iron soils · 14 mo used French oak · NOT Rioja",like:"Mellow Tempranillo",pair:"Bold meats"},
{name:"Bodegas Carchelo 'Altico' Syrah, Jumilla 2021",price:"24 / 96",notes:"black plum, pepper, savory herb",grape:"100% Syrah",story:"High-elevation limestone · 12 mo French oak, 1,100 cases",like:"Northern Rhône Syrah",pair:"Pintxos morunos, albóndigas"},
{name:"Blai Ferré i Just 'Ona' Priorat 2023",price:"15 / 60",notes:"ripe cherry, plum, licorice, mineral",grape:"Syrah, Garnatxa, Carinyena",story:"Hand-harvested, organic · all stainless, 600 cases · named for the daughter of our VinoVi supplier Nuria Estevé",like:"Fresh-style Priorat",pair:"Pintxos morunos, dátiles con chorizo"},
];
