const FOODILLUS={
plate:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="72" rx="92" ry="44" fill="#F6F1E3" stroke="#2E2422" stroke-width="3"/><ellipse cx="110" cy="72" rx="66" ry="30" fill="none" stroke="rgba(46,36,34,0.25)" stroke-width="2"/><ellipse cx="110" cy="70" rx="40" ry="16" fill="#C67B7B" opacity=".55"/><circle cx="96" cy="66" r="8" fill="#C39A4E" stroke="#2E2422" stroke-width="1.6"/><circle cx="118" cy="72" r="8" fill="#C39A4E" stroke="#2E2422" stroke-width="1.6"/><circle cx="107" cy="60" r="7" fill="#D7A85A" stroke="#2E2422" stroke-width="1.6"/><path d="M128 58 l6 -8 M131 58 l4 -9" stroke="#557B46" stroke-width="2.5" stroke-linecap="round"/></svg>',
cazuela:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><path d="M28 60 Q110 40 192 60 L184 96 Q110 112 36 96 Z" fill="#A85A3A" stroke="#2E2422" stroke-width="3"/><ellipse cx="110" cy="60" rx="82" ry="20" fill="#F0C48A" stroke="#2E2422" stroke-width="3"/><ellipse cx="110" cy="60" rx="70" ry="14" fill="#9E3B2E" opacity=".8"/><circle cx="90" cy="58" r="7" fill="#E8A75C" stroke="#2E2422" stroke-width="1.5"/><circle cx="118" cy="62" r="7" fill="#E8A75C" stroke="#2E2422" stroke-width="1.5"/><circle cx="134" cy="56" r="6" fill="#E8A75C" stroke="#2E2422" stroke-width="1.5"/><rect x="8" y="54" width="22" height="9" rx="4" fill="#A85A3A" stroke="#2E2422" stroke-width="2.5"/><rect x="190" y="54" width="22" height="9" rx="4" fill="#A85A3A" stroke="#2E2422" stroke-width="2.5"/></svg>',
paella:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="72" rx="96" ry="40" fill="#B9B4A6" stroke="#2E2422" stroke-width="3"/><ellipse cx="110" cy="70" rx="84" ry="32" fill="#E3A93B" stroke="#2E2422" stroke-width="2"/><ellipse cx="110" cy="70" rx="84" ry="32" fill="none" stroke="#9E3B2E" stroke-width="1.5" stroke-dasharray="3 5"/><path d="M70 66 q10 -12 22 0 q-11 8 -22 0z" fill="#9E3B2E" stroke="#2E2422" stroke-width="1.5"/><path d="M120 76 q10 -12 22 0 q-11 8 -22 0z" fill="#9E3B2E" stroke="#2E2422" stroke-width="1.5"/><circle cx="102" cy="82" r="5" fill="#557B46" stroke="#2E2422" stroke-width="1.4"/><circle cx="140" cy="62" r="5" fill="#557B46" stroke="#2E2422" stroke-width="1.4"/><path d="M14 68 l-10 -6 M206 68 l10 -6" stroke="#2E2422" stroke-width="4" stroke-linecap="round"/><path d="M4 62 a6 6 0 1 0 0.1 0 M216 62 a6 6 0 1 0 0.1 0" fill="#2E2422"/></svg>',
board:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><rect x="22" y="36" width="176" height="72" rx="10" fill="#B98A5A" stroke="#2E2422" stroke-width="3"/><rect x="34" y="46" width="152" height="52" rx="6" fill="none" stroke="rgba(46,36,34,0.2)" stroke-width="2"/><path d="M48 58 l30 0 l0 30 l-30 0z" fill="#F3E3B1" stroke="#2E2422" stroke-width="1.6"/><path d="M84 54 q18 -10 36 0 q-18 12 -36 0z" fill="#B23A33" stroke="#2E2422" stroke-width="1.6"/><path d="M86 74 q18 -10 36 0 q-18 12 -36 0z" fill="#B23A33" stroke="#2E2422" stroke-width="1.6"/><circle cx="150" cy="66" r="14" fill="#E8862E" stroke="#2E2422" stroke-width="1.6"/><circle cx="144" cy="90" r="4" fill="#557B46"/><circle cx="156" cy="92" r="4" fill="#557B46"/><circle cx="166" cy="86" r="4" fill="#557B46"/></svg>',
dessert:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="96" rx="80" ry="22" fill="#F6F1E3" stroke="#2E2422" stroke-width="3"/><path d="M76 92 L84 52 L136 52 L144 92 Z" fill="#D9A15A" stroke="#2E2422" stroke-width="2.5"/><path d="M84 52 L136 52 L132 60 L88 60 Z" fill="#8B5A3C"/><path d="M96 92 q8 -30 28 -40" fill="none" stroke="#6B3E2E" stroke-width="5" stroke-linecap="round"/><circle cx="150" cy="60" r="10" fill="#C67B7B" stroke="#2E2422" stroke-width="1.6"/><circle cx="150" cy="60" r="4" fill="#9E3B2E"/><path d="M60 88 l-8 -14 M62 90 l-14 -6" stroke="#2E2422" stroke-width="2" stroke-linecap="round"/></svg>',
bowl:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 140"><ellipse cx="110" cy="56" rx="78" ry="20" fill="#F6F1E3" stroke="#2E2422" stroke-width="3"/><path d="M32 56 Q40 112 110 116 Q180 112 188 56" fill="#F6F1E3" stroke="#2E2422" stroke-width="3"/><ellipse cx="110" cy="56" rx="64" ry="13" fill="#C9C583"/><circle cx="90" cy="54" r="6" fill="#557B46" stroke="#2E2422" stroke-width="1.4"/><circle cx="126" cy="58" r="6" fill="#C39A4E" stroke="#2E2422" stroke-width="1.4"/><path d="M104 50 l14 4" stroke="#9E3B2E" stroke-width="3" stroke-linecap="round"/></svg>'
};
const FOOD=[
// ---------- APERITIVO ----------
{cat:"Aperitivo",name:"Quesos",ill:"board",drop:"A board of three Spanish cheeses with house accompaniments — tomato-pepper jam, seasonal jam, house pickles — served with torta de aceite.",ing:"Three Spanish cheeses (list them), tomato pepper jam, seasonal jam, housemade pickles, torta de aceite",all:"Gluten, dairy, nuts, allium",mods:"Any single item removed or on the side; cheeses can be swapped for dietary needs (pasteurized only, no goat's milk) — check with Chef",ut:"Small spoon (jam), knife",tip:"Always name every cheese on the board."},
{cat:"Aperitivo",name:"Quesos y Charcutería",ill:"board",drop:"Jamón serrano, lomo serrano and chorizo with cow, sheep and goat's-milk cheeses, Marcona almonds, tomato-pepper jam, membrillo, house pickles and Spanish crackers.",ing:"Jamón serrano, lomo serrano, chorizo, cow / sheep / goat cheese, Marcona almonds, tomato pepper jam, mixed pickles, Spanish crackers, membrillo, encurtidos",all:"Gluten, dairy, nuts, allium (pork)",mods:"Any single item removed or on the side; meats & cheeses can be swapped (pasteurized only, no goat's milk, no sausage) — check with Chef",ut:"Small spoon (jam), knife",tip:"List all meats and cheeses on the board."},
{cat:"Aperitivo",name:"Ensalada de Raíces",ill:"bowl",drop:"Fresh root salad — carrot, parsnip, beet, chioggia and radicchio — with spiced goat cheese and a cider-mustard vinaigrette, topped with pepitas.",ing:"Carrot, parsnip, chioggia & red beet, treviso/radicchio, apple cider vinaigrette (whole-grain mustard, honey, espelette), spiced goat cheese (sumac, urfa biber), pepitas, pimentón",all:"Dairy, nightshade, mustard, honey",mods:"No spiced goat cheese (dairy-free); no pepitas",ut:"Serving spoon"},
{cat:"Aperitivo",name:"Sardinas",ill:"plate",drop:"Tinned Spanish sardines in olive oil with salsa verde, piparra peppers and house-made spiced potato chips.",ing:"Sardines in EVOO, Matiz piparra peppers, salsa verde (parsley, garlic, olive oil), house chips (russet, pimentón dulce & picante, espelette, tomato powder, garlic & onion powder, MSG)",all:"Fish, allium, nightshade · fryer cross-contact (chips)",mods:"Sub baguette for chips; salsa verde on the side",ut:"Small spoon, knife",tip:"Matrix drop line was copied from the old mackerel dish — this one is rewritten from the ingredients. Confirm with Chef."},
{cat:"Aperitivo",name:"Almendras y Piña",ill:"plate",drop:"Brûléed pineapple with goat cheese and Marcona almond spread, served on a baguette crostini.",ing:"Brûléed pineapple, goat cheese–Marcona almond spread, baguette crostini, Maldon salt, olive oil",all:"Gluten, dairy, nuts, sunflower",mods:"None",ut:"None (finger food)"},
{cat:"Aperitivo",name:"Pan a la Catalana",ill:"plate",drop:"Garlic-rubbed crystal bread with grated tomato, olive oil and sea salt.",ing:"Crystal bread, beefsteak tomato, reserva sherry vinegar, olive oil, garlic, Maldon, parsley",all:"Gluten, nightshade, allium",mods:"Add jamón serrano; add boquerones",ut:"None"},
{cat:"Aperitivo",name:"Encurtidos",ill:"bowl",drop:"Mixed Spanish olives and house-pickled vegetables.",ing:"Gordal, Verdial, Cuquillo, Zorzaleña & Cornicabra olives; pickled cauliflower, carrot, garlic (orange zest, ñora chile, rosemary, thyme); cornichons",all:"Vinegar, citrus (allium)",mods:"None",ut:"Spoon, ramekin"},
{cat:"Aperitivo",name:"Buñuelos de Bacalao",ill:"plate",drop:"Crispy cod fritters with parsley and garlic, with a piquillo cream sauce for dipping.",ing:"Bacalao, flour, eggs, milk, garlic, parsley, onion, baking powder, piquillo cream (heavy cream, piquillo pepper)",all:"Dairy, allium, nightshade, eggs, fin fish, gluten · fryer cross-contact",mods:"None",ut:"None"},
{cat:"Aperitivo",name:"Anchoas con Piperrada",ill:"plate",drop:"White and brown anchovies on grilled baguette with house-made piperade.",ing:"Nassari brown anchovy, Nassari white anchovy (boquerón), piperade (garlic, scallion, shallot, red bell & cubanelle pepper, tomato, sherry vinegar, espelette, bay), cava vinegar, grilled baguette",all:"Fin fish, gluten, nightshade, vinegar, alcohol, sunflower",mods:"None",ut:"None"},
{cat:"Aperitivo",name:"Gilda Clásica",ill:"plate",drop:"Classic Gilda skewers — white and brown anchovy, manzanilla olive, piparra pepper and cornichon.",ing:"Brown & white anchovy, manzanilla olive, piparra/guindilla pepper, cornichon",all:"Fin fish, allium, nightshade, sunflower",mods:"None",ut:"None"},
{cat:"Aperitivo",name:"Ajo Blanco",ill:"bowl",drop:"A traditional Andalusian chilled almond soup, topped with green grapes and fine shavings of jamón.",ing:"Almonds, olive oil, sherry vinegar, garlic, green grapes, cucumber, jamón",all:"Tree nuts (almond), allium, vinegar, pork",mods:"No jamón",ut:"Soup spoon"},
// ---------- TAPAS ----------
{cat:"Tapas",name:"Crudo de Atún",ill:"plate",drop:"Sushi-grade bluefin tuna with serrano pepper, ginger, shallot, finger lime and a watermelon aguachile.",ing:"Bluefin tuna, shallot, ginger, serrano chili, cucumber, aguachile (watermelon, cilantro, cucumber, orange, lime), finger lime, olive oil, Maldon",all:"Fin fish, allium, nightshade, cilantro, citrus",mods:"None",ut:"Fork"},
{cat:"Tapas",name:"Tortilla Española",ill:"plate",drop:"Spanish tortilla of potato, shishito and onion, served with garlic alioli and salsa brava.",ing:"Potato, shishito peppers, onion, eggs, salsa brava (olive oil, white vinegar, cayenne, sweet & spicy paprika, garlic, tomato paste), garlic alioli (egg yolk, canola/EVOO, white wine vinegar), chives",all:"Eggs, nightshade, allium, vinegar",mods:"Alioli on the side; brava on the side; add jamón serrano",ut:"Knife"},
{cat:"Tapas",name:"Pimientos de Padrón",ill:"cazuela",drop:"Flash-fried shishito peppers dressed with lemon juice and smoked sea salt.",ing:"Shishito peppers, lemon, smoked sea salt, smoked EVOO, parsley",all:"Nightshade, citrus · fryer cross-contact",mods:"None",ut:"None",tip:"Sell it: 'Spanish roulette — one in ten is hot.'"},
{cat:"Tapas",name:"Dátiles con Chorizo",ill:"plate",drop:"Chorizo-stuffed, bacon-wrapped Medjool dates over Dijon membrillo, garnished with chives.",ing:"Medjool dates, ground chorizo, applewood bacon, Dijon membrillo (Dijon, membrillo, Isastegi cider, cider vinegar, espelette, EVOO)",all:"Stone fruit, nightshade, vinegar, Dijon/mustard, orchard fruit, pork, allium",mods:"None",ut:"None"},
{cat:"Tapas",name:"Flor de Alcachofa",ill:"plate",drop:"Grilled Spanish artichokes with lemon zest and grated salt-cured egg yolk, served with anchovy aioli.",ing:"Spanish artichokes, salt-cured egg yolk, lemon, anchovy aioli (garlic, egg yolk, olive oil, brown anchovy)",all:"Allium, egg, citrus, fin fish · gluten cross-contact",mods:"Aioli on the side; sub garlic aioli",ut:"Fork / knife"},
{cat:"Tapas",name:"Patatas Bravas",ill:"cazuela",drop:"Crispy fried potato cubes with salsa brava, garlic aioli and an optional sunny-side-up egg.",ing:"Potato, salsa brava (olive oil, white vinegar, cayenne, sweet & spicy paprika, garlic, tomato paste), garlic aioli (egg, olive oil, garlic, parsley)",all:"Nightshade, vinegar, allium, eggs · fryer cross-contact (fin fish & dairy)",mods:"Brava or aioli on the side; with or without fried egg",ut:"Spoon",tip:"#1 volume item on the menu."},
{cat:"Tapas",name:"Croquetas de Jamón",ill:"plate",drop:"Serrano ham croquettes with hazelnut romesco, topped with grated dehydrated jamón and parsley.",ing:"Jamón serrano béchamel (manchego, butter, flour, nutmeg, milk), egg, breadcrumb, hazelnut romesco (hazelnut, tomato, sweet pepper, allium, olive oil)",all:"Pork, dairy, gluten, egg, tree nuts, nightshade · fryer cross-contact (fin fish)",mods:"Romesco on the side; sub quince jam",ut:"None (finger food)"},
{cat:"Tapas",name:"Croquetas de Setas y Trufa",ill:"plate",drop:"Locally cultivated mushroom and black truffle croquettes over a truffle-porcini mayo, garnished with dehydrated porcini.",ing:"Local mushrooms, black truffle, house béchamel, egg, breadcrumb, truffle/porcini mayo, dehydrated porcini",all:"Dairy, gluten, egg · fryer cross-contact (fin fish & dairy)",mods:"Truffle aioli on the side",ut:"None (finger food)"},
{cat:"Tapas",name:"Croquetas de Manchego",ill:"plate",drop:"Manchego béchamel croquettes plated on quince jam, finished with grated 6-month manchego and parsley.",ing:"Manchego béchamel (egg, breadcrumb, manchego, butter, flour, nutmeg, milk), quince jam",all:"Dairy, gluten, egg, citrus · fryer cross-contact (fin fish)",mods:"Quince jam on the side",ut:"None (finger food)"},
{cat:"Tapas",name:"Croqueta de Gamba",ill:"plate",drop:"Prawn and squid-ink croquettes plated on black garlic aioli.",ing:"Prawn, squid ink, garlic, béchamel (butter, flour, nutmeg, white pepper, milk), egg, breadcrumb, black garlic aioli",all:"Dairy, gluten, egg, allium, crustacean · fryer cross-contact (fin fish)",mods:"Black garlic aioli on the side",ut:"None (finger food)"},
{cat:"Tapas",name:"Pulpo a la Gallega",ill:"plate",drop:"The classic Galician dish — tender octopus with smoked paprika, coarse sea salt and olive oil, served over saffron mashed potato.",ing:"Spanish octopus, pimentón dulce, saffron mashed potato (butter, heavy cream), shallot-onion-garlic, chives",all:"Allium, nightshade, fish, mollusk, dairy",mods:"No paprika; no mashed potato",ut:"Fork / knife"},
{cat:"Tapas",name:"Setas",ill:"plate",drop:"King trumpet mushrooms with shoyu, ají verde and puffed quinoa.",ing:"King trumpet mushroom, shoyu, ají verde, puffed quinoa",all:"Dairy, allium (soy)",mods:"Ají verde on the side; quinoa on the side",ut:"Spoon"},
{cat:"Tapas",name:"Gambas al Ajillo",ill:"cazuela",drop:"Seared Argentine shrimp dressed with garlic and Calabrian chili.",ing:"Argentine shrimp, garlic, chili de árbol / Calabrian chili, olive oil",all:"Crustacean, allium, nightshade, vinegar",mods:"None",ut:"Fork / spoon"},
{cat:"Tapas",name:"Pintxos Morunos",ill:"plate",drop:"Grilled marinated skirt steak with baby beets in balsamic reduction and a green tomatillo sauce.",ing:"Skirt steak (garlic, cumin, paprika, OJ, cinnamon, coriander, cayenne, lemon, sherry vinegar), grilled baby beets (balsamic, cumin), tomatillo salsa (garlic, onion, cilantro, lime, green chili)",all:"Allium, nightshade, citrus, cilantro, vinegar · gluten cross-contact in meat prep",mods:"Meat can be prepared separately for GF",ut:"Fork / spoon"},
{cat:"Tapas",name:"Pluma Katsu",ill:"plate",drop:"Panko-crusted Ibérico pork shoulder with sherry tonkatsu sauce and a Spanish coleslaw.",ing:"Ibérico pork shoulder, egg, breadcrumb, slaw (napa cabbage, green onion, pickled radish, carrot), sherry tonkatsu (ketchup, soy, sugar, sherry, Worcestershire, garlic, ginger)",all:"Pork, eggs, gluten, allium, sesame, nightshade, soy, fin fish (Worcestershire in katsu sauce) · fryer cross-contact (fin fish & dairy)",mods:"Katsu sauce on the side",ut:"Fork / knife",tip:"Fin-fish allergy: the katsu sauce (Worcestershire = anchovy) is the hidden risk."},
{cat:"Tapas",name:"Berenjena Frita",ill:"plate",drop:"Crispy fried eggplant drizzled with chili honey and pimentón, crumbled with blue cheese.",ing:"Eggplant, cornstarch, honey, chili sauce, pimentón, blue cheese, chives",all:"Dairy, nightshade · fryer cross-contact (dairy, fin fish, gluten, pork, nightshade)",mods:"No blue cheese",ut:"Serving spoon"},
{cat:"Tapas",name:"Mahi en Adobo",ill:"plate",drop:"Lightly battered and fried mahi-mahi finished with a lemon aioli.",ing:"Mahi-mahi, garlic, onion, paprika, sherry vinegar, cornstarch, lemon, eggs, canola oil",all:"Fin fish, eggs, allium",mods:"None",ut:"None"},
// ---------- PAELLA ----------
{cat:"Paella",name:"Señorito",ill:"paella",drop:"Seafood paella with mahi-mahi, calamari and prawns, finished with garlic aioli — 'señorito' because it's all peeled and ready to eat.",ing:"Saffron sofrito (onion, celery, tomato, piquillo, garlic), bomba rice, mahi-mahi, calamari, prawns, parsley, garlic aioli",all:"Fish, shellfish, mollusk, allium, nightshade, citrus",mods:"No garlic aioli; aioli on the side",ut:"Cuchara de paella",tip:"Top-dollar item on the menu."},
{cat:"Paella",name:"Valenciana",ill:"paella",drop:"The original — paella with chicken legs, romano and white beans, artichoke and saffron.",ing:"Saffron sofrito, chicken leg, bomba rice, romano bean, white bean, rosemary, artichoke, parsley, olive oil",all:"Allium, nightshade, citrus",mods:"None",ut:"Cuchara de paella"},
{cat:"Paella",name:"Rabo de Toro",ill:"paella",drop:"Paella with braised oxtail and piparra pepper.",ing:"Saffron sofrito, bomba rice, braised oxtail, piparra pepper, olive oil",all:"Allium, nightshade",mods:"No piquillo peppers; piquillo on the side",ut:"Cuchara de paella"},
{cat:"Paella",name:"Paella Primavera",ill:"paella",drop:"Traditional Spanish paella with seasonal vegetables — green beans, artichoke, zucchini, asparagus, piquillo and spinach.",ing:"Bomba rice, vegetable stock, green beans, artichoke, zucchini, green & white asparagus, piquillo, spinach, sofrito, saffron",all:"Allium, nightshade, legumes",mods:"None",ut:"Cuchara de paella",tip:"The vegan-friendly paella."},
{cat:"Paella",name:"Marinera Fideuà",ill:"paella",drop:"Fideuà — toasted fideo noodles in place of rice — with Argentine shrimp, crab, garlic and chile de árbol, finished with garlic aioli and grilled lemon.",ing:"Saffron sofrito, fideo noodles, gambas, crab, garlic, chile de árbol, olive oil, garlic aioli, grilled lemon",all:"Allium, nightshade, shellfish, citrus, gluten (fideo = wheat)",mods:"No garlic aioli; aioli on the side",ut:"Cuchara de paella",tip:"Not gluten-free — fideo is wheat pasta."},
// ---------- POSTRES ----------
{cat:"Postres",name:"Churros",ill:"dessert",drop:"Fried churros dusted with cinnamon sugar, with chocolate sauce and olive-oil caramel for dipping.",ing:"Churro batter (sugar, butter, flour, milk, eggs), chocolate sauce (cream, coffee, corn syrup, dark chocolate, cocoa), caramel (EVOO, sugar, cream, butter, corn syrup, vanilla paste)",all:"Dairy, eggs, corn, caffeine, gluten",mods:"None",ut:"None (finger food)",tip:"Pair with the Carajillo — top dessert seller."},
{cat:"Postres",name:"Tarta de Queso",ill:"dessert",drop:"Authentic Basque burnt cheesecake, offered in the traditional style.",ing:"Cream cheese, mascarpone, sugar, eggs, yolks, vanilla, salt, flour",all:"Dairy, eggs, gluten",mods:"None",ut:"Fork"},
{cat:"Postres",name:"Passionfruit Goxua",ill:"dessert",drop:"A Basque-inspired trifle of passion fruit curd, lemon chiffon cake and mascarpone mousse.",ing:"Passion fruit curd (purée, sugar, eggs, PORCINE gelatin, butter), lemon chiffon cake (egg, oil, lemon zest, GF flour), mascarpone mousse (mascarpone, cream, powdered sugar, vanilla)",all:"Pork (gelatin), alcohol, dairy, eggs",mods:"None",ut:"Spoon",tip:"Contains porcine gelatin — not vegetarian, not halal/kosher."},
{cat:"Postres",name:"Torrijas",ill:"dessert",drop:"Spanish 'French toast' — brioche soaked in rum-spiked vanilla custard, then caramelized.",ing:"Brioche (flour, yeast, milk, eggs, butter), soak (egg yolk, cream, milk, brown sugar, vanilla paste, Sailor Jerry dark rum — nutmeg, cinnamon, clove)",all:"Dairy, eggs, gluten, alcohol",mods:"None",ut:"Fork",tip:"Matrix drop line was copied from Arroz con Leche — this one is rewritten from the ingredients. Confirm with Chef."},
{cat:"Postres",name:"Tarta de Santiago",ill:"dessert",drop:"Traditional Galician almond cake dusted with powdered sugar — naturally gluten-free.",ing:"Almond flour, sugar, eggs, powdered sugar",all:"Tree nuts, eggs",mods:"None",ut:"Knife",tip:"The go-to dessert for gluten-free guests."},
{cat:"Postres",name:"Bizcocho de Chocolate y Pistacho",ill:"dessert",drop:"Dark chocolate and olive-oil brownie with pistachio and sea salt, with a side of vanilla ice cream.",ing:"Dark chocolate, butter, olive oil, brown sugar, eggs, flour, cocoa, vanilla, pistachio, sea salt, vanilla ice cream",all:"Tree nuts (pistachio), eggs, gluten, dairy",mods:"None",ut:"Dessert spoon"},
];
// diet: V vegan · VG vegetarian · P pescatarian · GF gluten-free · DF dairy-free · "X*" = only with the mod
